### ISSUE TITLE
inclusion of apps to google doc?

### ISSUE THREAD

**Issue by jadrake75** [aurelia/documentation#114]
Hi I have been working on my next revision of my stamp-web application which is written in Aurelia..... 

the readme needs to be updated to reflect more about the project, and I need to work on tests but I am actively developing it.  It does not really fit with "examples" or "demos" it is more like sample application.... someone may find some nice tricks or examples..... we are using a lot of it as an example in my "business work"....  I am sure as more people develop applications they will want to add them to the show-case or examples pile.....

https://github.com/stamp-web/stamp-web-aurelia

**Comment by EisenbergEffect** [comment]
We will have a showcase post beta.
