### ISSUE TITLE
need documentation on lifecycle of custom elements

### ISSUE THREAD

**Issue by adrianhall** [aurelia/documentation#118]
I just had a frustrating few hours with custom elements, working out the lifecycle (and specifically, figuring out that the class constructor is the wrong place to be fiddling with the DOM).  Need to document all the lifecycle events of a custom element together with example code on how and when to set them up.

**Comment by maverix** [comment]
+1  Found a good article that helped me out
http://shellmonger.com/2015/07/24/the-lifecycle-of-an-aurelia-custom-element/

**Comment by EisenbergEffect** [comment]
For future reference, the docs explain the view lifecycle here: http://aurelia.io/docs.html#extending-html
They explain the navigation (for router-created components only) lifecycle here: http://aurelia.io/docs.html#the-screen-activation-lifecycle

**Comment by maverix** [comment]
@EisenbergEffect Sorry, you are correct.  I was sure that I had read over the docs and didn't see it there.  But as I am always complaining about my users... people don't read!

**Comment by JoshMcCullough** [comment]
@EisenbergEffect Those links appear to be dead -- do you have a link to the current documentation which outlines the lifecycle events for view-models _and_ custom elements?

**Comment by AStoker** [comment]
The docs page for Aurelia has changed its navigation (it's based off the version now). This link should work. Go to http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.2.4/doc/article/cheat-sheet/7 and search for "The Screen Activation Lifecycle". It is however only for view-models, not custom elements. This page will give you some more details about the lifecycle though: http://aurelia.io/docs.html#/aurelia/templating/1.0.0-beta.1.2.7/doc/article/templating-html-behaviors-introduction/7  
The docs page don't have direct links to sections of the page (which would be nice), so you'll have to either search or scroll to get there.

**Comment by EisenbergEffect** [comment]
Actually, they do have links to the sections :) Expand the "ToC" on the left for an article and click on the section. The url is updated. Most people just don't notice the ToC :) We are making it more integrated for the next release. Also, search is coming.

**Comment by AStoker** [comment]
Would it be possible to get those sections to work with all headings (including sub headings)? Different topic for a different issue though :) I did not realize (despite me actually doing it) that the ToC links actually saved the location to come back to.
Super excited for search!

**Comment by ModernRonin** [comment]
for anyone coming here while googling:

what you're searching can be found at

http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/creating-components/3

Just to save folks a few minutes...

**Comment by tomtomau** [comment]
And for those that are coming here while Googling, again..

https://aurelia.io/docs/fundamentals/components

**Comment by JNotelddim** [comment]
every one of the links in this thread gave me a 404 😂

currently:
https://aurelia.io/docs/fundamentals/creating-components#the-component-lifecycle
https://aurelia.io/docs/fundamentals/creating-components#creating-a-component

or, to try and handle the inevitable link rot which has infected every other comment:
https://aurelia.io/docs/  > Search > "lifecycle" > "The Component Lifecycle"
https://aurelia.io/docs/  > Search > "components" > "Creating A Component"
