### ISSUE TITLE
aurelia ready for production environment?

### ISSUE THREAD

**Issue by weagle08** [aurelia/documentation#130]
I know this is not really the proper place for this, but I was just wondering if you would consider Aurelia ready for production? We are considering Aurelia and AngularJS 1.4 mainly because we like the 2 way binding capability that they both have for forms, and desire a full stack framework. I've watched your video and have gone through the getting started and really like what I see but am scared of potential gotchas down the line. Guidance?

**Comment by EisenbergEffect** [comment]
We are shooting for beta in 6-8 weeks. We will give that the official "go to production" stamp. However, bear in mind there still may be some changes. The reason for that is that the ES6 loader spec and web standards specs are still in flux and changes in the standards may force us to make changes as well. That's not within our control unfortunately. 

We are about to do some new released now. There's an update on that in the blog post we'll be posting along with that shortly.

**Comment by weagle08** [comment]
Thanks for the quick reply, nothing you stated there scares me too badly! Hopefully we can help contribute back if given the green light to use Aurelia!

Thanks! thanks! thanks!

**Comment by frankhommers** [comment]
Where will you put that stamp? ;-)

Any news on this?

**Comment by EisenbergEffect** [comment]
It's ready.

**Comment by colinshen** [comment]
will the api break change in beta？

**Comment by EisenbergEffect** [comment]
Please see this announcement: http://blog.durandal.io/2015/11/16/aurelia-beta-week-day-1-the-beta-is-here/

**Comment by stalniy** [comment]
@EisenbergEffect do you have burndown or milestone somewhere on github to see when the first RC will be out?
