### ISSUE TITLE
Code examples should have snippets for all supported languages

### ISSUE THREAD

**Issue by jedd-ahyoung** [aurelia/documentation#133]
At the moment, the documentation seems to favor ES7 with decorators, but there are some ES6 examples without decorators as well. It would be beneficial to a) standardize this and b) provide examples in all Javascript dialects, including (but not limited to) the following:

 * ES5
 * ES6
 * ES7 (full decorators)
 * ES7 (without property initializers, for examples that need it)

Supersets of JS can be supported as well, such as TypeScript and CoffeeScript.

I think that this can easily be achieved with the [Bootstrap tabs](http://getbootstrap.com/javascript/#tabs) feature; the Aurelia.io site already uses the Bootstrap Javascript component. As such, we could offer the code examples without affecting the document length too much by simply adding some HTML markup to support the tabs.

I think that this would go a long way towards helping people understand the specific examples in the documentation, while emphasizing the flexibility of Aurelia. Further, by establishing this practice now, we can set a precedent for later documentation examples.

I'm willing to work on the tabs feature, although I might need some assistance translating some of the code snippets. Anyone have any ideas? Objections?

**Comment by EisenbergEffect** [comment]
It's a bit early to do this. The new docs app we are working on will support multiple languages for every code sample. Once those are in place, we may need help translating to other languages. But, you will want to do this work on the new docs infrastructure when it is ready.

**Comment by jedd-ahyoung** [comment]
I may be wrong, but I feel as though it's needed now, in some cases. (I need it, at least, as I'm not using decorators.) I wouldn't think it would hurt too much to add the tab markup to the markdown, and then begin some of the code translation now -  unless those code examples specifically will be thrown away and replaced with new ones. I figured we'd be able to reuse the samples from the current documentation.

**Comment by EisenbergEffect** [comment]
The problem is that the infrastructure doesn't support what you want to do. The current docs are entirely markdown, not pure html.

**Comment by jedd-ahyoung** [comment]
Markdown supports HTML tags; in fact, the docs currently use HTML heading
tags. Based on that, I believe that the documents could support Bootstrap
tabs. (There would be some overhead in terms of reading and updating the
raw markdown, as there would be a bit more syntax involved.) Again, I could
go ahead and work on this. However, if this is something we simply don't
want to do - perhaps because we'll be replacing the code examples entirely
with new ones - that's okay as well.

**Comment by EisenbergEffect** [comment]
We've got the ability to handle this in the new docs app. We are planning ES 2015, ES 2016 and TypeScript.

**Comment by jedd-ahyoung** [comment]
Nice. I'll be happy to help with this. I will say that I would condone
supporting ES5 as well - yes, ES6/7 are the new hotness, but potential
Aurelians may mix and match featuresets from different specs. (For
instance, devs might use ES6 but opt not to use the `class` keyword - and
as such, people may be using ES5 object syntax instead of ES6 class syntax.
In this case, a lot of examples would be much different (really, anything
having to do with decorators, as well as the DI system I believe).

Then again, I don't have any statistics to back this up. Perhaps the
majority of people using Aurelia would be using ES6 and all ES5 syntax
would be a second-class citizen. I suppose you'd have to take a reading
from the community to determine whether this feature would be worth the
work.
