### ISSUE TITLE
Documentation how to use templates and compiler

### ISSUE THREAD

**Issue by mahtavata** [aurelia/documentation#136]
Could you add documentation how to use the built in compiler and templates in custom code. Accessing the compiler and compiling templates without the router is a powerful and good tool in applications. It gives a lot of flexibility and control for the programmer.

**Comment by EisenbergEffect** [comment]
Absolutely! Thank you for adding this issue to remind us!

**Comment by EisenbergEffect** [comment]
I've added these notes to our docs plan here: https://github.com/aurelia/documentation/issues/181
