### ISSUE TITLE
Clarify app-specific extensions best practice

### ISSUE THREAD

**Issue by heruan** [aurelia/documentation#138]
In Aurelia Docs it reads:
> Note: A recommended practice for your own apps is to place all your app-specific extensions, value converters, etc. into a resources folder. _Then create an index.js file that turns them all into an internal feature plugin._

How to create that `index.js` file?

**Comment by EisenbergEffect** [comment]
I think we have this now: http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.0.7/doc/article/app-configuration-and-startup In the section "Organizing Your App with Features"
