### ISSUE TITLE
Create Curated List for possible ui-plugins

### ISSUE THREAD

**Issue by joelcoxokc** [aurelia/documentation#14]
Create a curated list of plugins we can begin developing on. 

Current contains the following
COMPONENTS:
Buttons
Actions
Tabs
Collections
Collapsible
Select
Typehead
Dropdown
Modal
Dialog
Progress
Card
DataGrid
Table
Shadows
Grid
Color
Draggable

LAYOUT:
ui-main
ui-body
ui-section
ui-nav
ui-aside
ui-header
ui-footer
ui-view
ui-grid
ui-custom

Plugins:
uiLayoutService
uiToggle
uiAnimate
uiWaves
uiText
uiBg

**Comment by zewa666** [comment]
Not sure if this is included with Progress, but today I saw this (http://lightningtgc.github.io/material-refresh) on DailyJS. Maybe it would be cool to add something like this as well.

**Comment by EisenbergEffect** [comment]
Closing this for now. We will handle this elsewhere.
