### ISSUE TITLE
 npm install -g generator-aurelia issues "deprecated" warning

### ISSUE THREAD

**Issue by adriatic** [aurelia/documentation#143]
```
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
```

**Comment by EisenbergEffect** [comment]
I think you meant to report that over here: https://github.com/zewa666/generator-aurelia

**Comment by adriatic** [comment]
True - I was behaving too literally (looking into https://github.com/aurelia/documentation/blob/master/English/get-started.md I would (without thinking) stuff everything I find in the context of that article into issues list related to that repository)
