### ISSUE TITLE
Ref doesn't document when the element is available.

### ISSUE THREAD

**Issue by LordZardeck** [aurelia/documentation#151]
I was really confused when first trying to use the `ref` attribute. The element is not available during construction, and isn't available until the `attached` method is called. This should be documented to help others like me figure out where we can use it.

**Comment by EisenbergEffect** [comment]
We will add docs on this. Per the beta, refs are available earlier, in the `bind` callback :)

**Comment by EisenbergEffect** [comment]
I added notes to this issue so we don't forget to cover it in the upcoming article: https://github.com/aurelia/documentation/issues/181
