### ISSUE TITLE
Many times the word "instrinct" is used ...

### ISSUE THREAD

**Issue by JMerrill** [aurelia/documentation#154]
... most often in JSON as the name: value pair `"type": "instrinct"`

Is this a typo/mis-spelling of "intrinsic"? It seems pervasive. I have not seen (but cannot say I've looked exhaustively) anywhere that code is looking for the value "instrinct".

If in fact this should be "intrinsic" I would be willing to try to fix it everywhere.

**Comment by EisenbergEffect** [comment]
It's a bug in the actual TSDoc library that we are using to generate the json doc file I believe. I think it's literally a typo in their code. I'll follow up with them.
