### ISSUE TITLE
src folder should not be deleted

### ISSUE THREAD

**Issue by fabioluz** [aurelia/documentation#159]
I'm updating the pt-br version of the Get-Started.md. After translating the file, I'm following the tutorial, step by step, to see if there is any error. I found something that might be a problem.

The Get-Started says the following:

"You may examine the provided index.html file and the rest of the files in src and dist, however we recommend deleting these folders before moving on with this tutorial. By doing so, you can more effectively learn how to build an Aurelia app from scratch."

However, if I delete src folder, the file `main.js` is deleted too (of course); and this file is not being created again throughout the tutorial, which causes an error that breaks the app.

Because of that, I believe that src should not deleted. Or Am I wrong?

**Comment by EisenbergEffect** [comment]
You shouldn't need main.js for the getting startup guide, I don't think, not if you use the html for index.html that is provided in the tutorial.

**Comment by fabioluz** [comment]
Yeah, you're right. I thought that the html provided in the tutorial was the same as the one provided by the navigation skeleton project. Looking carefully, I see that there is a difference in the aurelia-app attribute. My bad. 

Thank you!
