### ISSUE TITLE
Need high resolution Aurelia logo

### ISSUE THREAD

**Issue by scriswell** [aurelia/documentation#165]
Ideally a resolution independent SVG file but high res bitmaps at the least for "retina" displays.

**Comment by joelcoxokc** [comment]
@scriswell Do we already have one?

**Comment by scriswell** [comment]
@joelcoxokc Rob, has access to the latest logo in SVG format.

**Comment by EisenbergEffect** [comment]
@joelcoxokc Is this fixed?

**Comment by EisenbergEffect** [comment]
@joelcoxokc @scriswell Is this fixed?

**Comment by scriswell** [comment]
The high resolution logo is on the website that much I can confirm. We need
to use the same logo file on the docs for now.

**Comment by EisenbergEffect** [comment]
Can we close this now?

**Comment by jdanyow** [comment]
(removing from the bug list)

**Comment by EisenbergEffect** [comment]
I'm just going to close this.
