### ISSUE TITLE
Useless fields initialization in TS examples

### ISSUE THREAD

**Issue by jods4** [aurelia/documentation#170]
I was not sure where to report this, but I noticed that in the new documentation many TypeScript examples assign fields in their ctor. For example, from "Declaring dependencies" in the cheat sheet:

```ts
export class CustomerDetail {
  constructor(private dep1: Dep1, private dep2: Dep2){
    this.dep1 = dep1;
    this.dep2 = dep2;
  }
}
```

The two lines in the ctor are redundant with the TS generated code. 

When you put a visibility modifier before a ctor parameter it actually does two things:
- It means you declare a class field with the specified visibility and the same name as the parameter.
- It initializes the generated field with the parameter value.

**Comment by glen-84** [comment]
Somewhat related, and possibly subjective: It seems overly-explicit to specify types when the variable is being assigned a value that can be used to infer such information. For example:

```ts
firstName: string = 'John';
```

The type hint is unnecessary here IMHO. Same with void return types.
