### ISSUE TITLE
add scrollbars to document reader articles

### ISSUE THREAD

**Issue by Thanood** [aurelia/documentation#171]
First of all: great work releasing beta1 and the new docs!

I did not find the repository for the new documentation reader released yesterday, so I'm trying it here. Hope it's okay.. :-)

There are some articles that are quite long but don't display a scrollbar - at least on chrome desktop. It'd make it easier to see how much text is still available on the page and that - at least for me - is easier to read.

For instance the [cheat sheet](http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.0.1/doc/article/cheat-sheet).

I've added the following style in developer tools to make that happen for me.
```css
au-view.content {
    height: 100%;
    overflow: auto;
}
```

I would have issued a PR but didn't find a repo for the new reader.

**Comment by airboss001** [comment]
I like the scroll bars for exactly the same reason.

**Comment by EisenbergEffect** [comment]
@joelcoxokc Definitely need this fixed. They were working and then they disappeared at some point. FYI It's not possible to scroll the docs at all on Android.

**Comment by joelcoxokc** [comment]
oh yikes! I'll have it fixed by EOD
