### ISSUE TITLE
Scroll position when navigating between different topics

### ISSUE THREAD

**Issue by airboss001** [aurelia/documentation#172]
Seems the topic page scroll position is remembered, but is its a global position and not the position in  the topic where you were viewing.

For instance if I am reviewing binding and am down toward the bottom of the page, and then navigate to templating I get placed somewhere down in the page that I have no reference (I did not navigate there) and have to scroll back to the top to get context again.

If you are going to remember position it should be for each topic page, not just a global scroll position I believe.

Thanks, looking great!

**Comment by EisenbergEffect** [comment]
We made a quick fix to scroll articles to the top when you navigate.
