### ISSUE TITLE
The new docs don't work with an iPad

### ISSUE THREAD

**Issue by smolinari** [aurelia/documentation#173]
My browser is Safari.

![image](https://cloud.githubusercontent.com/assets/3314957/11282411/7e8a417c-8eff-11e5-9553-ff38f64f8d9f.jpg)

Scott

**Comment by joelcoxokc** [comment]
@smolinari Thank you for letting us know. We will get to it ASAP.

**Comment by paulroho** [comment]
Same here (Firefox & Chrome on Android).

**Comment by EisenbergEffect** [comment]
Can someone confirm whether or not this is still an issue?

**Comment by smolinari** [comment]
I can confirm the docs work now on iOS with Chrome, Safari and Mercury.

However, the script type picklist doesn't work. I'll close this issue and open a new one. 

Scott
