### ISSUE TITLE
Make all headings externally linkable (in narrative style docs and API docs)

### ISSUE THREAD

**Issue by jdanyow** [aurelia/documentation#174]
It would be great if we could share links to specific points within the docs (gitter, github issues, stackoverflow, etc).  This was possible in the preliminary docs site but the feature hasn't been carried forward into the new docs application yet.

A good example of how this could work is github's logic for rendering markdown documents.  It renders heading markdown as a heading element with a link that appears when you hover over the heading:
![hover](http://i.imgur.com/5dCjPrx.png)
![markup](http://i.imgur.com/g6DBbEy.png)

Clicking on the link changes the url and scrolls the page to the heading:
![clicked](http://i.imgur.com/q8zZ6As.png)

Ultimately this enables sharing links to specific sections of the markdown document.  GitHub has similar logic that enables linking to specific lines of code in the source.

It would be awesome if this capability was added to the aurelia docs app and resulted in a reusable intra-view router component. I've seen questions in the gitter about how to do things like this without breaking the standard routing logic.

**Comment by txels** [comment]
I think this is sorely needed in places like http://aurelia.io/docs.html#/aurelia/framework/latest/doc/article/cheat-sheet - it is currently not possible to just share a link to a specific "cheat".

**Comment by ryanwischkaemper** [comment]
It is also sorely needed to incorporate some sort of sub-menu's for each help topic in the topic menu on the left hand side of the screen. The *Cheat Sheet* topic is the longest by far, but some of the others are long as well. With no way to directly navigate to subtopics within each main topic, we are forced to do an inordinate amount of scrolling. For me personally, it makes me wish the old docs were back.

**Comment by EisenbergEffect** [comment]
Yes, we've already designed and prototyped a sub-menu UX for the docs along with externally linkable headers. Before we can finish that work we need to do some core work on our docs format. That's in process now.

**Comment by ryanwischkaemper** [comment]
That's great news. Nice job on everything else related to the docs

**Comment by EisenbergEffect** [comment]
Released. The heading aren't clickable, but there's a slide out panel on the left with the TOC for each article. Clicking on those will update the url so that you can link to section.
