### ISSUE TITLE
Getting Started and Docs on Aurelia.io don't load in IE 11 nor Edge

### ISSUE THREAD

**Issue by awright18** [aurelia/documentation#175]
![aurelia docs on ie 11](https://cloud.githubusercontent.com/assets/1014386/11342028/d89ff8d2-91ca-11e5-9a19-6411969256ab.PNG)
This is what I get when trying to look at the getting started on IE 11 and Edge. Chrome is fine. 
This is the url I'm hitting http://aurelia.io/docs.html#/aurelia/framework/latest/doc/article/getting-started
Forgive me if this is the wrong repo. I couldn't find the one with the official site code.

**Comment by Petoj87** [comment]
For me it works in IE 11 but on in Edge there the page just becomes white, but if I hit F12 (opening debug tools) and reload the page it works...

**Comment by EisenbergEffect** [comment]
We are working on this. We have it tracked elsewhere so I'm going to close this for now. It appears to be a race condition of some sort. We're tracking it down.
