### ISSUE TITLE
New docs have a few mistakes in code examples

### ISSUE THREAD

**Issue by timfish** [aurelia/documentation#176]
http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.0.2/doc/article/cheat-sheet

I'm guessing the `</table>` closing tags should not be in the following:

Illegal Select Code

```
<template>
  <select>
    <template repeat.for="customer of customers">
      <option>...</option>
    </select>
  </table>
</template>
```

Correct Select Code
```
<template>
  <select>
    <option repeat.for="customer of customers">...</option>
  </table>
</template>
```

**Comment by nomack84** [comment]
@timfish `</table>` closing a `select`? Typo perhaps?

**Comment by nomack84** [comment]
@timfish perhaps could you make a PR, that's clearly wrong.

**Comment by timfish** [comment]
Does this repo cover the latest docs? From a quick browse these looked like the old docs...

**Comment by adriatic** [comment]
Sometimes it is a lot easier to the owner of this document to simply delete the line than to go through the formal process (generate PR) :-)

**Comment by timfish** [comment]
I would happily do a PR to help as I've been gifted aurelia for free. However, I think this repo is for the old docs. I only added this issue as there isn't yet a way to contribute to the new docs...

**Comment by timfish** [comment]
Scrap that. I've found the new docs in: https://github.com/aurelia/framework/

**Comment by timfish** [comment]
Spoke too soon. What I've actually found is the HTML files for the new docs but I suspect they don't edit them manually and they're generated from markdown. I'll leave this open till I find out...

**Comment by EisenbergEffect** [comment]
Fixed.
