### ISSUE TITLE
Incorrect instruction on aurelia.io under section 'Running The E2E Tests'

### ISSUE THREAD

**Issue by kaveh82** [aurelia/documentation#177]
Under section **Running The E2E Tests** there's a mention of a build command **gulp webdriver_update** but this didn't work and after looking through the build tasks for e2e I realized the correct command to be **gulp webdriver-update**

**Comment by EisenbergEffect** [comment]
I'll get it updated in the next docs push. Thanks!

**Comment by EisenbergEffect** [comment]
Fixed internally. Going out with the next release.
