### ISSUE TITLE
Script selection picklist in the docs doesn't work on iOS

### ISSUE THREAD

**Issue by smolinari** [aurelia/documentation#179]
Hi,

Using the docs, they work now with iOS (for iPad). Thanks for fixing that. 

However, the top right selection for the script type doesn't work. Tested with Safari, Chrome and Mercury.

Scott

**Comment by EisenbergEffect** [comment]
@joelcoxokc Can you look into this?

**Comment by EisenbergEffect** [comment]
Major update coming next week with new ux...
