### ISSUE TITLE
but in documentation code example.

### ISSUE THREAD

**Issue by caperaven** [aurelia/documentation#180]
import {inject, customAttribute, DOM} from 'aurelia-framework';

DOM is not found in aurelia-framework it is found in aurelia-pal

see
http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.0.6/doc/article/cheat-sheet

**Comment by EisenbergEffect** [comment]
This is an issue with the Babel transpiler. It actually is found in aurelia-pal but is also re-exported in aurelia-framework.

**Comment by caperaven** [comment]
I used it as per documentation and it did not work.
Only when I used it with pal did I manage to get it working.
So if the documentation is right there is another issue.

**Comment by EisenbergEffect** [comment]
Yes, that's what I'm saying. The problem is in Babel. We are trying to track it down and see if we can get them to fix it.
