### ISSUE TITLE
older versions of docs have no content

### ISSUE THREAD

**Issue by Gheoan** [aurelia/documentation#182]
For example [here](https://github.com/aurelia/skeleton-navigation/issues/226#issuecomment-162091072) I am linking to version `.../1.0.0-beta.1.0.3/...`  of docs and there is no content on the page.

Tested in Firefox and Chrome

**Comment by Gheoan** [comment]
@EisenbergEffect is this being worked on? One solution would be to always use `latest` as version for docs.

**Comment by EisenbergEffect** [comment]
We need to get this fixed. Sorry for the delay.

**Comment by Gheoan** [comment]
[`1.0.0-beta.1.0.5` works](http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.0.5/doc/article/what-is-aurelia)

[`1.0.0-beta.1.0.4` does not work](http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.0.4/doc/article/what-is-aurelia)

https://github.com/aurelia/framework/compare/1.0.0-beta.1.0.4...1.0.0-beta.1.0.5

**Comment by EisenbergEffect** [comment]
Right, those should be updated to the latest compatible version. We'll look into this.

**Comment by EisenbergEffect** [comment]
Ok, we have this fixed in master. It will go out in the next week.
