### ISSUE TITLE
Change router config moduleId to src folder

### ISSUE THREAD

**Issue by oswaldomilet** [aurelia/documentation#183]
In "2. Get Started" section, instead of:
```
config.map([
    { route: ['', 'welcome'], name: 'welcome', moduleId: './welcome', nav: true, title: 'Welcome' }
]);
```
should be:
```
config.map([
    { route: ['', 'welcome'], name: 'welcome', moduleId: './src/welcome', nav: true, title: 'Welcome' }
]);
```

**Comment by EisenbergEffect** [comment]
We think this may be a regression in system.js. We are investigating this week. But, the src folder shouldn't need to be included if everything were working correctly.

**Comment by oswaldomilet** [comment]
ok, thanks for the quick response.
