### ISSUE TITLE
Production Setup (ASP.NET 5) missing information

### ISSUE THREAD

**Issue by oswaldomilet** [aurelia/documentation#184]
I was following the "3. A Production Setup" and chose skeleton-typescript-asp.net5, however I'm very confused about gulp tasks available.

In tutorial says to run  "gulp watch", but project didn't open on http://localhost:9000.

Besides that, in which case I run each of the task available?

For example:

- I want to run my ASP.NET backend, which task should I bind to "After Build"?
- in case of deploy, what to run? build or bundle?
- should I run "clean" task or it's called by other tasks?
- does build task runs bundle task?

**Comment by PWKad** [comment]
The ASP.NET skeletons have their own README.md file which shows how to run the applications.  The general documentation is for the general skeletons which aren't specific to the backend framework.

**Comment by oswaldomilet** [comment]
Thanks, this saved my day. But now I'm having the following error when "gulp bundle":

```
[13:33:09] Starting 'bundle'...
[13:33:10] 'bundle' errored after
[13:33:10] Error on fetch for dist/app.html at file:///C:/app/src/skeleton-navigation-typescript-vs/wwwroot/dist/dist/app.html.js
        Error: ENOENT: no such file or directory, open 'C:\app\src\skeleton-navigation-typescript-vs\wwwroot\dist\dist\app.html.js'
    at Error (native)
```

note the "dist/dist", I have changed nothing in the project.

**Comment by ahmedshuhel** [comment]
@oswaldomilet The bundle task is broken the the main branch right now. This [PR](https://github.com/aurelia/skeleton-navigation/pull/264) should fix it.

**Comment by oswaldomilet** [comment]
Thanks, it worked
