### ISSUE TITLE
How to unit test custom element including DOM manipulation

### ISSUE THREAD

**Issue by danielabar** [aurelia/documentation#186]
Followup from gitter discussion with PWKad:

Q: Does anyone know how to unit test a custom element that does dom manipulation? I did this in Angular 1.x with [karma-ng-html2js-preprocessor](https://github.com/karma-runner/karma-ng-html2js-preprocessor) which compiles templates and makes them available for loading into tests, then you can run your directive code in the test, and use jquery to verify the dom manipulation. For Aurelia, I did read [this post](http://patrickwalters.net/unit-testing-your-es6-view-models-my-best-practices-for-aurelia/) on testing custom elements but doesn't seem to have a solution for the dom manipulation

A: what do you want to test? Seems like you want to test the browsers Dom api
I mean that if you want to see that your code actually manipulates the Dom it is testing the browsers Dom implementation, if you want to test that the api is called just stub it out

Q: For example, I have a custom element that wraps an svg circle, representing a node on the graph. If user clicks on the node, a border animates in to indicate selected, and if they click again, the border animates out. I'd like to test that. Have done that sort of thing before as a unit test with karma-ng-html2js-preprocessor. It's faster and easier than setting up e2e test, and can focus on just one component rather than the whole application flow
Another example, this component responds to changes in data properties by moving the node to a different position, would also like to test that

A: Open an issue on documentation repo perhaps we could prioritize a doc to help with that kind of testing.There are already a few docs mentioned in there we are working on.

**Comment by EisenbergEffect** [comment]
We've got a new `testing` library that enables full unit testing of components.

**Comment by EisenbergEffect** [comment]
Docs here: http://aurelia.io/hub.html#/doc/article/aurelia/testing/latest/testing-components
