### ISSUE TITLE
node-gyp rebuild errors on fresh installed windows 10.

### ISSUE THREAD

**Issue by vegarringdal** [aurelia/documentation#187]
Hi
Got a few "node-gyp rebuild" errors when doing "npm install" following the "getting stared" guide.
It was on a fresh installed windows 10 virtual pc I made just for Aurelia, was kinda confused why I started getting errors when everything just worked when I followed the "getting started" last time.
Did a few searched on my friend "google" then I tried this:
-started with a fresh windows again to make sure nothing was messing with me.
-installed Microsoft visual studio community 2015 (c++ and python tools, and Microsoft web developer tools)
-installed python 2.7.11 (with option add to path)

After this I followed the "getting stared" again, and I did not get any errors with node-gyp rebuild
Do not know if you need all the options I selected on the Microsoft visual studio community 2015, but wrote down the ones I did install.

Might be nice for others noobs like me to know about, nothing more depressing when trying something new and the "getting stared" fails on you.

**Comment by EisenbergEffect** [comment]
Closing this. I believe it's addressed by new setups with cli and webpack. Also, I think it's a "red herring" and shouldn't cause any real issues.
