### ISSUE TITLE
Problem with "Getting Set Up" section in "Getting Started" doc

### ISSUE THREAD

**Issue by jwatkin** [aurelia/documentation#188]
On this page:
http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.1.2/doc/article/getting-started,
in the "Getting Set Up" section, the TypeScript Kit download displays a blank page when dragging the index.html file into Firefox under a Windows 7 (and perhaps elsewhere). The index.html file in the ES 2016 Kit correctly displays "Welcome to Aurelia!". An older TypeScript Kit download from December 2015 works.

Also, the instructions for opening the index.html file from within VisualStudio 2015 don't work for me, for either kit. In VisualStudio 2015 (Enterprise), when I choose File > Open > Web site..., all I see in the dialog box are folders within the downloaded kit folder, no files.

Thank you,
Jim

**Comment by EisenbergEffect** [comment]
Thank you for reporting this Jim. Something is indeed wrong with the TypeScript beginner kit. I'm not sure how that happened. I confirmed it was working properly last week. I'll investigate and get a fix out.

Regarding using VS code, you will want to open the folder as a web site.

**Comment by jwatkin** [comment]
Thank you for your prompt reply. I was unfamiliar with opening web sites in Visual Studio but now I understand. Can I suggest this alternative text for your documentation?

**Visual Studio** - Open Visual Studio 2015. Using the main menu, select File > Open > Web site... In the resulting dialog, choose the starter kit folder then click the Open button. The folder contents will be displayed in the Visual Studio Solution Explorer window. Right click on index.html in Solution Explorer and select "View in Browser". This will fire up IISExpress and serve index.html.

**Comment by EisenbergEffect** [comment]
Ok, we've updated the docs. We didn't realize that the Firefox method won't work with the TS kit, but only the ES2015 kit. The docs reflect that now as well as your recommended clarification for use with VS.
