### ISSUE TITLE
Setup for Getting Started missing JSPM Install

### ISSUE THREAD

**Issue by jimnorth55** [aurelia/documentation#189]
I was following the Getting Started docs, using the TypeScript kit and ran into an issue as soon as I did the first mods to app.ts and app.html.   After entering the "Welcome" model and template, I ran the app and got a JS error (" submit() is not a function").  Upon inspection, it was apparent that app.ts was not being loaded.  I suspected a JSPM issue, and of course then realized that JSPM was not installed.  After installing JSPM, the app ran fine.

Unless I missed something, the Getting Started needs to have some setup instructions added.

**Comment by EisenbergEffect** [comment]
No form of installation should be needed for the beginning kit. If you had to run jspm, then there may be a bug. We will investigate.
