### ISSUE TITLE
improve documentation about ref

### ISSUE THREAD

**Issue by k2s** [aurelia/documentation#191]
I learned today on Gitter about `view-model.ref`.
It is mentioned in cheat sheet and also there is this article http://drdwilcox.blogspot.sk/2015/12/aurelia-leveraging-viewmodel-of.html.

But it is not in https://github.com/aurelia/documentation/blob/master/English/docs.md#ref.

I would like to create pull request, but don't have the feeling I understand it good enough. For example what is `controller.ref="someIdentifier"`. The word controller is new for me in context of Aurelia.

Could you please clarify this in documentation ?

**Comment by EisenbergEffect** [comment]
The docs in the documentation repo are no longer valid. We should remove them. The cheat sheet online is the official source now.

**Comment by EisenbergEffect** [comment]
Latest docs contain the appropriate information.
