### ISSUE TITLE
Missing font

### ISSUE THREAD

**Issue by DevNebulae** [aurelia/documentation#192]
When visiting any link of a part of the documentation I notice the font is the default font. This is easily reproduced by visiting any of the links in the Libraries section of the documentation. Some quick links:

- [BindingBehavior](http://aurelia.io/docs.html#/aurelia/binding/1.0.0-beta.1.1.3/doc/api/class/BindingBehavior)
- [bootstrapper](http://aurelia.io/docs.html#/aurelia/bootstrapper/1.0.0-beta.1.1.2/doc/api/overview)

Adding the Source Code Pro font to the website should do the trick.

**Comment by EisenbergEffect** [comment]
@scriswell Can you check this out? It looks fine to me but you are the "font man" :laughing:

**Comment by DevNebulae** [comment]
@EisenbergEffect @scriswell I suspect you have the font installed on your computer, but I don't. This is what it looks like to me.

![capture](https://cloud.githubusercontent.com/assets/12952123/13345662/f12f345e-dc60-11e5-8fd3-2bced62b1a3e.PNG)

Adding this CSS rule should resolve the issue:

```
@font-face {
    font-family: "Source Code Pro";
    src: url(path/to/font);
}
```

**Comment by EisenbergEffect** [comment]
Major update coming next week...
