### ISSUE TITLE
How to use third party JQuery plugins with Aurelia

### ISSUE THREAD

**Issue by rajvirtual** [aurelia/documentation#193]
Hi Guys,
This is the library i am trying to shim.
https://github.com/aehlke/tag-it

This library is dependent on jquery and jquery-ui

I am using this command to shim

jspm install github:aehlke/tag-it -o "{ registry: 'jspm', main: 'js/tag-it', shim: { 'js/tag-it': { deps: ['jquery','jquery-ui'],exports:'$' } }, dependencies: { jquery: 'github:components/jquery','jquery-ui':'github:components/jqueryui@1.11.4'}, format: 'global' }"

This is my Aurelia class,

```
import 'bootstrap'';
import  'jquery-ui';
import 'aehlke/tag-it';

  attached() {
    $('.txtEdit').tagit({
      allowSpaces: true,
      readOnly: true,
    });
  }

```
It's not throwing any errors in console when the method tagit is called, but it does not do anything.
The debugger goes into jquery.js file and does not execute any code from tag-it.js file.
Is it something i am using incorrectly to load these libs ?

Thanks !

**Comment by rajvirtual** [comment]
Since its a JQuery UI  $.Widget extension it is suppose to call the _createWidget method inside JQuery UI and that is not happening. I wonder why ? i can see the JQuery-UI module loaded correctly in chrome debugger.

**Comment by rajvirtual** [comment]
When i changed my Markup to use a class selector, instead of ID, the plugin is working now.

` <input type="text"  class="form-control input-lg txtEdit" />` is working
` <input type="text"  id="txtEdit"  class="form-control input-lg" />`  does not work.

@EisenbergEffect , is there any preference in using one or the other ?

Thanks !

**Comment by EisenbergEffect** [comment]
If you have only one element that needs the widget, then give it a `ref` and you can pass it directly to your jQuery control.

```html
<input type="text" ref="txtEdit" class="form-control input-lg" />
```

```javascript
bind() {
  $(this.txtEdit).tagit({
      allowSpaces: true,
      readOnly: true,
    });
}
```

If you have multiple controls, then you can use selectors, but  you should always scope them:

```
@inject(Element)
class MyComponent {
  constructor(element) {
    this.element = element;
  }

  bind() {
    $('selector', this.element).plugin();
  }
}
```
