### ISSUE TITLE
Dash docset for Aurelia

### ISSUE THREAD

**Issue by riddla** [aurelia/documentation#194]
First of all: you got a great looking documentation over at http://aurelia.io/docs.html.

I started to generate a Dash docset for Aurelia (https://kapeli.com/dash and https://zealdocs.org for Windows) over at https://github.com/riddla/aurelia-docset, because I got used to those kind of documentation browsers over the last years. I know a lot of colleagues in our field also use those API browsers and I think the aurelia community could benefit from such a "docset".

At this early point of my attempt any insights from the aurelia team would be helpful. As I presume that the official docs have some clever ways to generate them from Markdown to HTML and to also feed the API section at http://aurelia.io/docs.html#/api/home – can you give me any insights into your process? Or maybe something like my little project is already on your roadmap?

**Comment by dlo83** [comment]
+1 for Dash docset.  Dash is a great tool.

**Comment by EisenbergEffect** [comment]
We'd love a community member to tackle this if it's interesting to them. Ultimately, our hub will have much more than docs and integrate other information streams, so it will be the best source of information available. However, a dash docset is always welcome. All the docs are available in public repos in the `doc` folder of each repo. Articles are written in markdown. They have a basic header and a couple of custom elements, but those should be easy to parse with something like common mark if you need.
