### ISSUE TITLE
Left-nav disappears after scrolling to page bottom in iOS landscape orientation

### ISSUE THREAD

**Issue by jwatkin** [aurelia/documentation#195]
On this page:
http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.1.3/doc/article/what-is-aurelia

1. Rotate the iOS device to landscape orientation.
2. Scroll the right pane to the bottom of the page.
3. Scroll the right pane to the top of the page.
4. The left-nav document list is missing.

Tested on:
* iPhone 5S with iOS 9.2.1 under Safari and Chrome
* iPhone 6 with iOS 9,2 under Safari

**Comment by EisenbergEffect** [comment]
@joelcoxokc We've got a few issues on the docs app we'll need to address soon. I'm thinking we should devote next week to trying to fix a few things there. Let's try to include this issue in that list. We can discuss in our status meeting tomorrow.

**Comment by jwatkin** [comment]
The anomaly seems to happen after any device orientation change. If one opens the page in landscape orientation and then changes to portrait orientation the problem will also occur. If one maintains the orientation used to open the page, landscape or portrait, the page is fine.

**Comment by EisenbergEffect** [comment]
@joelcoxokc Let's do this before we do the structural changes. I'd like to get a release out with this and the couple other bugs fixed, then we can work on the major changes we discussed tonight.

**Comment by jwatkin** [comment]
Your new Docs deployment, with a left-nav slide-out for mobile, has fixed this issue on my iPhone. Thank you.

**Comment by EisenbergEffect** [comment]
Awesome!
