### ISSUE TITLE
Docs are not responsive

### ISSUE THREAD

**Issue by Gheoan** [aurelia/documentation#197]
The docs are missing the `viewport` `meta` tag making the media queries useless and the page not responsive.

**Comment by EisenbergEffect** [comment]
@joelcoxokc Before we do the structural update we discussed tonight, let's get this a the other bugs in the current docs fixed so I can do a release. Once I get that release out, let's move ahead to the structural update.

@Gheoan Sorry about this! It's a regression in our mobile platform detection. We'll get it fixed soon.

**Comment by Gheoan** [comment]
This seems to be fixed.
