### ISSUE TITLE
Consider documenting all internal Aurelia tags and their implementing modules

### ISSUE THREAD

**Issue by oising** [aurelia/documentation#198]
For example, <content></content> for content projection in a template is not documented (that I can see.) It would be nice to a have a matrix of internal tags/elements, or at least ensure all are mentioned in the cheat sheet.

**Comment by EisenbergEffect** [comment]
Yes, we will have it. Incidentally, `content` is not Aurelia-specific. It is part of Shadow DOM v0. We will be updating to Shadow DOM v1 `slot` in the near future. Explanation of this will be in upcoming documentation.

**Comment by oising** [comment]
Thank you Rob.

**Comment by EisenbergEffect** [comment]
I believe that most of this is in the cheat sheet. There are also new docs coming for templating and binding that should catalog everything.
