### ISSUE TITLE
Unexpected behavior with the Aurelia Docs mobile left-nav slide-out

### ISSUE THREAD

**Issue by jwatkin** [aurelia/documentation#199]
I'm experiencing an unexpected behavior with the Aurelia Docs mobile left-nav slide-out. When tapping on an article within the slide-out, or attempting to change to the other tab within the slide-out, the first tap doesn’t have any perceived effect. One has to tap again to get the desired effect. This happens with Safari, but not Chrome, on:
iPhone 5S, iOS 9.2.1
iPhone 6. iOS 9.2

Also, one would expect to be able to switch back and forth between the tabs without closing the slide-out. Instead, one can switch tabs from Articles to LibrariesAPI once without closing the slide-out but whenever switching from LibrariesAPI to Articles, the slide-out will close. This happens with both Safari and Chrome.

**Comment by EisenbergEffect** [comment]
New UX coming next week.
