### ISSUE TITLE
Tailoring the "A Production Setup > Running The App" doc for each skeleton

### ISSUE THREAD

**Issue by jwatkin** [aurelia/documentation#200]
I realize it’s still early days and you have more planned, so please just think of this as a friendly To Do list item. In my Windows 7 environment, the instructions for starting up the Aurelia app in the "Running The App" section on this page:
http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.1.4/doc/article/a-production-setup
don't seem to work for the "skeleton-typescript-asp.net5" version. Instead of using "gulp watch" as instructed, one needs to follow the instructions in the "src\skeleton-navigation-typescript-vs\README.md file. Perhaps the Aurelia Docs page should include a reference to this alternate documentation to prevent some VS folks from giving up before they get started.

I also noticed that Visual Studio will attempt to build the project and throw a bunch of errors, which might scare some people away. Fortunately, Visual Studio provides an option to use the last successful build (from the "gulp build" command mentioned in the README.md instructions). When this "last successful build" option is used, VS will open a browser window to a different port than what’s documented, but the app runs fine there. The documented port, 9000, will also work once this instance is running but it’s not the port in the URL that VS opens the browser to.

So within the "Running The App" section, maybe each skeleton should get its own paragraph of instructions, or a reference to its external documentation.

**Comment by EisenbergEffect** [comment]
We'll be replacing this process with an Aurelia CLI which will set things up based on your choices. We're also working with Microsoft to integrate this into Visual Studio.
