### ISSUE TITLE
Api Documentation

### ISSUE THREAD

**Issue by irashid25** [aurelia/documentation#201]
Hi all,

I've recently started to develop an app using aurelia and am looking to learn and understand the framework from the ground up.

While i know the framework is in beta, does anyone have any idea when the Api(library) documentation will be updated with examples on how to use them.

For example, If you look at the addRoute method on the router class
addRoute
(
config: RouteConfig
navModel: NavModel
): void 

Parameters:

config: RouteConfig
The [[RouteConfig]].
navModel: NavModel
The [[NavModel]] to use for the route. May be omitted for single-pattern routes.

And that's all there is. It would be so much beneficial if there was also an example on how to use this, especially for new aurelia developers like myself. Unless there is documentation that i have missed, the developer in some cases will have to search online for practical examples of how the method is used. Looking at the above someone could ask, what exactly is a routeconfig? What properties does it have if its an object etc.

Contrast this to msdn documentation (yes i know, it's taken along time in the making).
Datetime compare example: 
https://msdn.microsoft.com/en-us/library/system.datetime.compare(v=vs.110).aspx

It gives you an overview of the method just like the aurelia docs, but then it gives an example on how it should be used including additional information that will be useful to the developer. I dont need to search anywhere else on how this method is used. All i have to figure out is where the best place is to use it.

The team may already have plans to do something like this, but it would be nice to have an update as to whether this is being looked at. I feel for developers it would be really useful as it would allow them to learn the framework themselves rather than trawling stackoverflow for answers to common tasks. 

Thanks

**Comment by EisenbergEffect** [comment]
Did you look in the cheat sheet?

**Comment by irashid25** [comment]
Thanks for the super quick reply rob.

I have just done a ctrl f on the following page and did not find an example of the addroute method.
http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.1.4/doc/article/cheat-sheet

Another issue i came across that helps me make my point is the following:

Yesterday i was just playing around and made 2 buttons that redirected a user to the signup view and the login view. On the click handlers (methods in the js file) i tried the new redirect method/class to navigate the user to the correct view. It didn't work. I looked at the api docs and like i described above it was just an overview. Then i looked at the cheatsheet and the only real example i could find was the following:

return next.cancel(new Redirect('login')); (found in the customizing the navigationpipeline section). 
In the end, after searching stackoverflow and github forums i was able to achieve my objection by doing the following:

import {Aurelia, inject} from 'aurelia-framework';
@inject(Aurelia)
export class Welcome{
    constructor(aurelia){
        this.aurelia = aurelia;
    }
    
    login(){
        this.aurelia.setRoot('pathtojsfile');
    }
    
    signup(){
        this.aurelia.setRoot('pathtojsfile');
    }
}

the welcome view is the default view that i load using the configure method.
export function configure(aurelia) {
    // here you can configure any optional plugins
    aurelia.use
           .standardConfiguration()
           .developmentLogging();
           
    // Set the default component to load (if none is provided it will load app.js)
    aurelia.start().then(a => a.setRoot('welcome/welcome'));

};

My point is, i don't know why using the new redirect method didn't work in my situation and why the setRoot did. I feel if the documentation was a bit more complete it would really help new JavaScript developers, like myself, understanding the framework much easier. Apologies if i sound like I'm wanting to be spoon fed, but as a .net developer who uses the msdn documentation on a regular basis, i feel the documentation is a bit lacking for non JavaScript developers in terms of examples. That being said, comparing the docs to something like Angular, the docs are very very good and excellent for someone to get started.

Thanks.

**Comment by EisenbergEffect** [comment]
Yes, we are planning more docs ;)
FYI, there aren't docs on `addRoute` because it's not something people really use. They use `map`: http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.1.4/doc/article/cheat-sheet/7

**Comment by irashid25** [comment]
Good to know,

I will assume in the mapping its the name property i pass in the redirect or the setroot method, and the router will take care of the rest. I will test out later tonight.

Thanks for your time rob. Really appreciate it.

**Comment by EisenbergEffect** [comment]
More stuff is on the way. Stay tuned. We know the docs need more content.
