### ISSUE TITLE
Trouble loading JQuery plugin

### ISSUE THREAD

**Issue by Tinadim** [aurelia/documentation#202]
I'm trying to load a jquery plugin in one of my views:

    import $ from 'jquery';
    import 'select2';
    import 'select2/css/select2.css!';

And then, calling

    bind() {
        $('selector').select2();
    }

However, it keeps complaining that select2 is undefined:
`aurelia-logging-console.js:86 ERROR [app-router] TypeError: $(...).select2 is not a function(…)`

Debugging this point, shows me that $ jquery is loaded ok, but select2 is undefined. Looking at the source files, shows me that the select2.js is loaded. Also, my config file seems to be ok:

    map: {
        ...
        "select2": "github:select2/select2@4.0.2"
    }

Am I doing anything wrong? Do I need to do something else to import the plugin?

**Comment by Gheoan** [comment]
This is related to how `select2` is exported and how `systemjs`/`jspm` loads it, not to `aurelia`.

**Comment by Tinadim** [comment]
@Gheoan It also happened with other jquery plugins but anyway... do you have any clue on how to fix, it?

**Comment by Gheoan** [comment]
@Tinadim Try this from the command line:
```shell
jspm install select2 -o "{ format: 'global' } 
```

**Comment by Tinadim** [comment]
@Gheoan That worked just fine, thanks! I'll take a look into the jspm docs to get to know better the install options.
