### ISSUE TITLE
Documentation site doesn't load on Safari

### ISSUE THREAD

**Issue by AStoker** [aurelia/documentation#203]
Trying to load the doc site (http://aurelia.io/docs.html) in Safari, and the page does not load up, but rather stays on the splash screen. The page works in Chrome, however. 
Looking at the network tab in Safari, all requests are finished, so there isn't some pending request. There are also no issues displayed in the console.

**Comment by EisenbergEffect** [comment]
I just tried it and it worked fine for me. Can you provide any other information?

**Comment by brandonseydel** [comment]
Same here i just did verified in browsertack I am working with @AStoker on gitter to solve this issue.

**Comment by AStoker** [comment]
I'm running the OS X El Capitan Beta, so that might have something to do with it. However, another user in the Aurelia Gitter channel had the same issue. I tried opening the site with both the Safari Technology Preview (which just came out last week and has 98% of ES6 functionality, awesome), but also the release version of Safari. I can manage to run the skeleton project just fine on all the browsers... 
![screen shot 2016-04-08 at 7 35 58 pm](https://cloud.githubusercontent.com/assets/2907279/14400074/59145226-fdc1-11e5-9f36-b13b025d8646.png)

**Comment by brandonseydel** [comment]
@AStoker Whats the warning?

**Comment by AStoker** [comment]
Huh, looks like a bluebird error, but was logged as a warning.

![screen shot 2016-04-08 at 7 39 40 pm](https://cloud.githubusercontent.com/assets/2907279/14400099/ab78e964-fdc1-11e5-8699-6aa48ae5b564.png)

**Comment by AStoker** [comment]
However, this warning only comes up on the Technology Preview, not regular Safari. This is probably do to polyfills breaking things that are already implemented. This is the case for Fetch right now in the Tech Preview.

**Comment by AStoker** [comment]
Just something to track (and reiterating), this only is breaking inside of the Safari Technology Preview. The STP is implementing the latest version of WebKit which has 99% ES6 functionality (http://kangax.github.io/compat-table/es6/#webkit). This is what is going to be released soon with Safari, so it's worth looking into why it's not working now.

**Comment by EisenbergEffect** [comment]
@joelcox please take a look

**Comment by AStoker** [comment]
Closing this story. The documentation site now loads up. Not sure if it's related to the new Aurelia Hub site changes, or the most recent Safari TP release. In either case, we're good to go.
