### ISSUE TITLE
Http Client doco location?

### ISSUE THREAD

**Issue by jsobell** [aurelia/documentation#204]
I notice these have been moved to `old`, meaning nobody will bother looking at them, so where do users go for documentation on the HttpClient?
Am I missing something, or might these be best reinstated until the missing sections have been transitioned to the proper document project?

**Comment by EisenbergEffect** [comment]
Regarding HttpClient, this was an oversight. I'll re-instate that document. Everything else is on the official docs site and the source for the docs are in the repos that they relate to under the doc folder.

**Comment by EisenbergEffect** [comment]
About to publish docs that include this information this week.
