### ISSUE TITLE
GetStarted ...

### ISSUE THREAD

**Issue by JimmiV** [aurelia/documentation#205]
... doesn't load on Edge.
I click on the button on the home page but the loader spins continuosly

**Comment by EisenbergEffect** [comment]
We are aware of this issue. It is a bug in SystemJS. We are working on a
solution.

**Comment by AStoker** [comment]
Is this related to https://github.com/aurelia/documentation/issues/203?

**Comment by EisenbergEffect** [comment]
I'm not sure. It loads fine in Safari for us...

**Comment by EisenbergEffect** [comment]
I'm closing this issue since we are tracking it elsewhere. We have a new docs implementation coming soon and we'll seek to address this as part of that.
