### ISSUE TITLE
Documentation site not loading in Edge

### ISSUE THREAD

**Issue by gc435** [aurelia/documentation#207]
I'm trying to load the Getting Started documentation in Edge, but it gets stuck at the splash screen.  The spinner just spins.

Curiously, the page loads if I have Edge's dev tools open.

The link I'm trying is http://aurelia.io/docs.html#/aurelia/framework/latest/doc/article/getting-started.

Edge version 25.10586.0.0
EdgeHTML version 13.10586

**Comment by EisenbergEffect** [comment]
Sadly, this is a bug in the module loader SystemJS which is out of our control. We are working to provide other setups which don't use this library in the future. For now, try keeping the dev tools open if you wish to use Edge, or use another browser. We understand this isn't acceptable for deploying an app. For actually building production apps, we have a Webpack kit that works better. We're also working on a CLI that uses RequireJS, which also makes things better.

We sincerely apologize. We've been having increasing problems with the SystemJS library recently so we're working to remove it for the future.

**Comment by gc435** [comment]
Thanks for the update.  I'm brand new to Aurelia, and still trying to wrap my head around all the required tooling.

It sounds like as you move to RC, Edge will be fully supported by both Aurelia and its recommended tooling.  I know this must be a major hassle when things are out of your control though.

**Comment by EisenbergEffect** [comment]
Thank you for your kindness and for understanding. We are working hard on a simpler, reliable toolset for the future :)
