### ISSUE TITLE
Advanced templating: store original textContent

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/documentation#208]
Originally posted at aurelia/templating/issues/340, moved here at the suggestion of @EisenbergEffect.

I'm not sure, but I think this may be a fairly common scenario: wanting to pass data to a custom element through the element content, rather than any attribute. E.g.:

```html
<my-note-editor>Lorem ipsum

This is my current note.</my-note-editor>
```

I've had this scenario come up multiple times in my current project. I've found a solution which may be a nice example of custom template processing to add to the docs. My solution is a decorator that stores the original content on the element reference and then injecting the element reference into the constructor and reading it out.

```ts
import {processContent} from "aurelia-framework";

export function saveElementTextContent() {
	return processContent(function(compiler: any, resources: any, element: Element) {
		(<any>element).originalTextContent = element.textContent;
		element.textContent = "";
		return false;
	});
}
```

```ts
@autoinject
@saveElementTextContent()
export class MyNoteEditor {
	constructor(element: Element) {
		this.note = (<any>element).originalTextContent;
	}
}
```

I'm fairly happy with this. I'd like it even better if the original `textContent` could be directly injected through some custom Type, but I haven't looked into implementing that yet.

**Comment by EisenbergEffect** [comment]
@RomkeVdMeulen Have you tested that this works correctly cross browser? I thought I checked that custom properties were not cloned and that using get/set attribute was required.

**Comment by RomkeVdMeulen** [comment]
I've tested it in Chrome, I'll check other browsers monday.

I'm sorry, I didn't follow that last part.

**Comment by EisenbergEffect** [comment]
So, if you have an element and you see element.myProp on it and then clone the element, do you still have a myProp on the clone. I was pretty sure that didn't work and that an attribute via the setAttriubute api was required.

**Comment by RomkeVdMeulen** [comment]
You're right. I can't get it to work now. Strange, I could've sworn it worked at some point.

I'm not entirely happy with this construction anymore anyway. It may just be simpler to use `@processContent(false)` and then store and clear the element content in the constructor.

```ts

@autoinject
@processContent(false)
export class Testsaver {
	public note: string;

	constructor(element: Element) {
        this.note = element.textContent;
		element.textContent = "";
    }
}
```

Pretty compact, and more transparent as well.

**Comment by RomkeVdMeulen** [comment]
I'll just close this.
