### ISSUE TITLE
Event Aggregator: includeEventsIn

### ISSUE THREAD

**Issue by mttmccb** [aurelia/documentation#210]
This sounds interesting but I can't quite picture how it could be used. It sounds like it's a way to inherit (the term used in the docs is mix) event aggregator functionality.

Do anyone have a more concrete example?

**Comment by mttmccb** [comment]
I can see it's used by the config object to add the event aggregator functionality to the aurelia instance

**Comment by EisenbergEffect** [comment]
It instantiates a new instance of event aggregator and merges its methods into the object you provide so that the obj now has pub/sub capabilities.
