### ISSUE TITLE
Event Aggregator: config options

### ISSUE THREAD

**Issue by mttmccb** [aurelia/documentation#211]
There is a mention of config options, are there any options for EventAggregator?

Looking at the source code it doesn't appear so, could it explicitly mention this in the docs? Maybe the fact the config object used the includeEventIn method would be a good example?

**Comment by EisenbergEffect** [comment]
I'm not quote following the question. Can you explain a bit more for me? Thanks!

**Comment by mttmccb** [comment]
Might be easier if I put it in a pull request, I'll find the right repo and do it hopefully later tonight
