### ISSUE TITLE
Fix search

### ISSUE THREAD

**Issue by jimmywarting** [aurelia/documentation#212]
I find it particularly hard to search for something since the docs don't have any search then I'm left to using google. But google don't bring up so good result either. Maybe cuz it's SPA and google having problem crawling them.

I hope you fix google crawling bot and also build a search functionality on the website as well. So that we don't have to skim through the hole api do find how to use X

**Comment by EisenbergEffect** [comment]
Yes, there several items we are planning related to this:

* A better ToC feature coming in the next release which will make it easier to see the contents of an article at a glance. 
* A search feature built into the docs.
* Server-side rendering for Aurelia itself, which we will then utilize in our docs app to enable better SEO.

**Comment by rquast** [comment]
+1

**Comment by EisenbergEffect** [comment]
Next week....

**Comment by rquast** [comment]
It's still not getting indexed, and I still can't search "PushState" even though it's in the content (under Cheat Sheet).

**Comment by rquast** [comment]
I'm up to a point in my app now where I'm trying to work on the SEO.. so a guide and a working example of this would really help.

**Comment by EisenbergEffect** [comment]
The SEO piece for our docs isn't implemented yet. For that we need server-side rendering. The basics of that have just begun. You are welcome to contribute. If you can't wait for that feature, there are services available which will do server render for SEO for you.

**Comment by rquast** [comment]
Thanks for the update and advice. After reading about Google's indexing requirements for JS sites, I've come to the conclusion that server-side rendering is the best option. I'll try a service if I can't figure out something with PhantomJS.
