### ISSUE TITLE
Very minor - typo

### ISSUE THREAD

**Issue by massimocode** [aurelia/documentation#213]
On here:
http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.2.4/doc/article/app-configuration-and-startup

`ineract` should be `interact`

**Comment by massimocode** [comment]
Also on here:
http://aurelia.io/docs.html#/aurelia/dependency-injection/1.0.0-beta.1.2.3/doc/article/dependency-injection-basics

`paramter's` should be `parameters'`

**Comment by massimocode** [comment]
I would put in a PR but I can't find the source code for the documentation online

**Comment by EisenbergEffect** [comment]
You can find the source for the docs in the doc folder of the respective repo, under the articles sub-folder. So, for the first doc, that's in framework and the second one is in dependency-injection.

**Comment by massimocode** [comment]
Thanks, I've created PRs here:
https://github.com/aurelia/dependency-injection/pull/101
https://github.com/aurelia/framework/pull/441
