### ISSUE TITLE
Getting started 'Adding Navigation' does not work

### ISSUE THREAD

**Issue by maximusmusterus1** [aurelia/documentation#214]
In the Getting Started guide at chapter 'Adding Navigation', the router is configured in app.js via a configureRouter(…) method. The method does not get called and therefore the router is not configured properly. I've also seen the introduction video, where Rob uses dependency injection and set up the router within the constructor. This way, everything works as expected.
So either the guide is out of date, the test bundle is out of date or I'm doing something completely wrong. :D Please let me know what is the expected place to configure the router. I'm starting fresh with this framework and want to do things right from the beginning. (For what i can say, I think the DI/constructor set up looks reasonable and modular so I think this is the way to go.)

**Comment by EisenbergEffect** [comment]
The video is out of date. You should have a `configureRouter` method on your component.

**Comment by maximusmusterus1** [comment]
Thanks :)
