### ISSUE TITLE
Documentation on aurelia.io cannot be printed

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/documentation#215]
@erikvullings commented on [Sat Jun 11 2016](https://github.com/aurelia/skeleton-navigation/issues/493)

Not really related to this repo, but couldn't find another way to mention it...

I like to read documentation on my ebook reader. However, I could neither send it properly, nor print it. I've tried several browsers (chrome, ie, edge), but none of them could print the pages (they stop at the first page, in chrome even overlapping the content).

And just as a side note: the eligibility of the tips/warning font is not very clear, and my TypeScript setting is never saved. 

---

@Vheissu commented on [Thu Jun 23 2016](https://github.com/aurelia/skeleton-navigation/issues/493#issuecomment-228238870)

This is definitely not the right place to post this. I would post it on the `aurelia framework repo`

**Comment by EisenbergEffect** [comment]
I'm closing this as a dupe. We are considering a solution of generating pdfs or all our articles automatically and making that available as a download.

**Comment by erikvullings** [comment]
@EisenbergEffect would you also consider generating mobi or epub versions for eBook readers?

**Comment by EisenbergEffect** [comment]
We would have to research that. Is there a node.js plugin to create those formats from html?
