### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dbowser** [aurelia/documentation#216]
Where can we see a roadmap / plan for Aurelia?
I am porting our app from Silverlight and really need to be able to know when things like a powerful datagrid component will be available. We did a LOT with datagrid and in place editing with valueconverters and all so need that same level of functionality to do much with Aurelia. I have been general references to something coming but no details. Kind of hard to plan and manage a project without more info. Now that we are close to 3rd Q 2016 I was very hopeful some more details would be forthcoming.

**Comment by EisenbergEffect** [comment]
We don't have a release date for our own datagrid that we can share at this time. However, one of the strengths of Aurelia is that it is highly interoperable with other libraries. There are many datagrids available that you could choose from. I'd recommend looking for one that meets your unique requirements and just dropping that into Aurelia wherever you need it. One nice example is the Keno datagrid. There's even an Aurelia-Kendo bridge project that provides an Aurelia API for the Kendo grid so it works as a native Aurelia component. You can learn more here: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge
