### ISSUE TITLE
Documentation cannot be read on Windows Phone 10

### ISSUE THREAD

**Issue by erikvullings** [aurelia/documentation#217]
The spinning just never stops...

**Comment by patrickrobbins** [comment]
What browser are you using?

**Comment by AStoker** [comment]
Could this be related to the issue where the documentation site doesn't load in Edge?

**Comment by EisenbergEffect** [comment]
It loads on Edge and IE 11. Both were tested.

**Comment by AStoker** [comment]
Gotcha, yah, works now with the new Beta site up. Did y'all switch to Webpack, or are you still using SystemJS/JSPM on the doc site?

**Comment by AStoker** [comment]
@erikvullings, potentially silly question. Have you cleared your cache and tried navigating to the root page (http://aurelia.io/hub.html)? I had a brief moment of worry yesterday as my browser had cached the site and my url was no longer valid (and gave me the spinner). Just want to make sure we're covering all the basis.

**Comment by EisenbergEffect** [comment]
The HUB is built using the Aurelia CLI, which uses NPM for package management and RequireJS for its loader. It has its own build system, similar to Webpack, but capable of using different module loaders.

**Comment by EisenbergEffect** [comment]
So, does it also work on the phone?

**Comment by erikvullings** [comment]
OK, I've tried again, and now it is working (sort of). 
The page loads, but it cannot be used since I cannot collapse the menu. See the attached screenshot (Edge browser on Windows Phone 10 - I've used also another browser, Maxthon, with similar results).

![image](https://cloud.githubusercontent.com/assets/3140667/16344125/50ea761e-3a3b-11e6-87f2-1ffd5cdd6419.png)

**Comment by EisenbergEffect** [comment]
Sure. That's a different issues. Our initial release wasn't designed primarily for mobile since most developers will use this at their desktop. We are tracking mobile issues and will have a mobile UX update. Since we've already got that tracked, I'll close this issue.
