### ISSUE TITLE
Documentation translation to other languages

### ISSUE THREAD

**Issue by tolemac** [aurelia/documentation#218]
Is there any planning to translate documents into other languages?
And not only that, but I wonder, is it necessary?

Personally I think that translating documents into other languages ​​is something that ultimately is harmful, because it never gets to have timely updates for new versions.

That being so, what would be the best way to bring Aurelia people who do not master the English language?

Personally I have not mastered 100% English, and when I start working with a new technology or product, I need to concentrate enough to read the documentation, this is heavy but only at first, once I understand the technology I can read easily the rest of the Documentation. If I found an initial documentation, something that makes me a good introduction to the product I save me a bad drink.

This initial document in my language should not be a translation of the documents into my language, should be an additional document to help me understand the English documentation. A document that talk about what are the key concepts of the technology that will see in the product documentation.

This document in my language should not take many snippets as these are subject to changes in the product and be forced to have to change that document each version in each language.

What do you think about?

**Comment by EisenbergEffect** [comment]
The docs app is designed to support multiple languages, including version tracking across translations on individual sections of each doc so that we can show when it's out of date with the English version. We've still got a bit more tech to build around other languages, including swaping individual sections of a doc between your native language and English.
