### ISSUE TITLE
missing some general Binding documentation

### ISSUE THREAD

**Issue by dkent600** [aurelia/documentation#219]
Hi, when I click on "Binding" under "Articles", I see info about ValueConverters and Behaviors, but nothing about the basics of binding in general, including the syntax for binding expressions.  I've seen information about types of bindings, somewhere.  I've actually never been able to find information *anywhere* about the syntax of binding expressions.  I'd love to see these.

Thanks,
Doug

**Comment by EisenbergEffect** [comment]
Yes, @jdanyow is working on an article with the basics. It should be ready soon.
In the mean time, you need to go to the cheat sheet. That has most of what you want to know.
