### ISSUE TITLE
search shortcut does not work when using Chrome on Windows 7

### ISSUE THREAD

**Issue by josh-egan** [aurelia/documentation#221]
Using Chrome on Windows 7

When I hit Ctrl + Shift + P in an attempt to open up the search box, I get the print dialog.

**Comment by EisenbergEffect** [comment]
LOL Yes. Yes. A bit of an oversight. We'll get it fixed. Thanks!

@joelcoxokc Just a reminder when you get a chance, we need a different key combo for Windows at least :) But, have a nice weekend first. We've been really busy this week. Take a break.

**Comment by EisenbergEffect** [comment]
Closing this as a duplicate. We've got it tracked elsewhere. Thanks!
