### ISSUE TITLE
Hub Site's Side Nav

### ISSUE THREAD

**Issue by diahron** [aurelia/documentation#222]
Is there a way to hide the side-bar on the Hub Page. It would be nice to get it out the way. Most api has this feature. It would be nice to implement it.  Just a thought.

**Comment by lmj0011** [comment]
Yes, this is a problem for mobile viewers

**Comment by eshell** [comment]
+1

**Comment by EisenbergEffect** [comment]
Hopefully releasing an update next week :)

**Comment by adzm** [comment]
Documentation inaccessible on mobile entirely due to this.

**Comment by EisenbergEffect** [comment]
We've got it fixed and are releasing it in the next day or so.
