### ISSUE TITLE
Aurelia Hub Navigation Skeleton

### ISSUE THREAD

**Issue by amourrashid** [aurelia/documentation#223]
Hello;
   Can you please provide us a Navigation skeleton  like the one used in the Aurelia HUB.
This is very useful for Developing a large application with many modules such as an ERP including lets say HR Module,Payroll,General Ladger,Accounts Receivable,Accounts Payable,Inventory,Assets etc.

Thank you very much.
Amour Rashid
Dar Es Salaam
Tanzania

**Comment by EisenbergEffect** [comment]
We can't provide our HUB directly and it would take a lot of work to clean that up and turn it into a general purpose app kit. However, we are planning to release some kits like this. I'm closing this for now since we have this tracked internally.

**Comment by amourrashid** [comment]
Thank you Rob

Sent from Yahoo Mail on Android 
 
  On Sun, 26 Jun, 2016 at 13:23, Rob Eisenberg<notifications@github.com> wrote:   
We can't provide our HUB directly and it would take a lot of work to clean that up and turn it into a general purpose app kit. However, we are planning to release some kits like this. I'm closing this for now since we have this tracked internally.
