### ISSUE TITLE
Ctrl+Shift+P not a suitable key binding on any major browser

### ISSUE THREAD

**Issue by PeterWone** [aurelia/documentation#224]
Hub is gorgeous and slick with a quite good UX. However, the keyboard shortcut Ctrl+Shift+P for searching is not a good choice.
- Internet Explorer Ctrl+Shift+P invokes privacy mode (aka porn mode). 
- Microsoft Edge Ctrl+Shift+P invokes privacy mode. 
- Chrome Ctr+Shift+P invokes the Print dialog.
- Firefox Ctrl+Shift+P invokes privacy mode. 

How about Ctrl+Shift+F which appears to be uncommitted on all browsers? It's a better mnemonic anyway: F for Find.

**Comment by Alexander-Taran** [comment]
there is no ~~spoon~~ hub
don't know where info about shortcut came

maybe can be closed

**Comment by EisenbergEffect** [comment]
implementation changed
