### ISSUE TITLE
cheatsheet section on databinding doesn't include oneTime, oneWay and twoWay

### ISSUE THREAD

**Issue by dkent600** [aurelia/documentation#225]
This example is given in the binding behaviors section, but not in the cheat sheet in the databinding section where .one-way, etc are discussed:

<span>${foo & oneTime}</span>

Similarly for oneWay and twoWay.

I would expect to find these in both places.

**Comment by Alexander-Taran** [comment]
maybe you could pull up a PR?
https://github.com/aurelia/framework/blob/master/doc/article/en-US/cheat-sheet.md

**Comment by Alexander-Taran** [comment]
can be closed

**Comment by EisenbergEffect** [comment]
Yep. Appears to have been fixed.
