### ISSUE TITLE
databinding cheat sheet section doesn't talk about binding expressions and the fluent api

### ISSUE THREAD

**Issue by dkent600** [aurelia/documentation#226]
I see you've nicely updated the databing section in the cheat sheet, but are still missing some important stuff (in my mind).  So just in case, I'd like to see treatment of:

1) syntax of binding expressions that include javascript and '|' and '&' and whatever else can go in
2) use of relevant fluent API, such as BindingEngine.propertyObserver, etc

Thanks

**Comment by EisenbergEffect** [comment]
We've got extensive databinding documentation on the way :) We're tracking it across multiple issues elsewhere so I'm going to close this one for now. Thanks!
