### ISSUE TITLE
databinding in the cheat sheet should go in the higher-level "Binding" section. 

### ISSUE THREAD

**Issue by dkent600** [aurelia/documentation#227]
It seems to me that a lot of the information under databinding in the cheat sheet should go in the higher-level "Binding" section where folks are most likely to go to find that info.  Perhaps rename the "Binding" section to "Data Binding".

**Comment by EisenbergEffect** [comment]
Yes, it's being worked on by @jdanyow We should have that soon.

**Comment by jdanyow** [comment]
I'll have this done this week- hang in there

**Comment by EisenbergEffect** [comment]
Thanks @jdanyow You've done so much amazing work!

**Comment by dkent600** [comment]
Yes! (Amazing work!)

**Comment by jdanyow** [comment]
sorry @dkent600 - the holiday weekend snuck up on me- I'm working on it this week.

**Comment by dkent600** [comment]
@jdanyow No pressure  :-)

**Comment by jdanyow** [comment]
this has been implemented and will go out with the docs app update this week
