### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by erdoll** [aurelia/documentation#230]
Nice update to the documentation with the new HUB approach.  However, if one wants to print say the Getting Started Guide, a print friendly format is not available.  The default print format is hopeless.  Google Simplify Page does not help.  It would be nice to be able to print the documentation - for those of us that like to consume it that way instead of on the screen.

**Comment by EisenbergEffect** [comment]
I'm closing this as a dupe. We are considering a solution of generating pdfs or all our articles automatically and making that available as a download.
