### ISSUE TITLE
Hub app freezes up

### ISSUE THREAD

**Issue by dkent600** [aurelia/documentation#232]
Steps:

0) In the Edge browser (haven't tried others)
1) start fresh from home page "http://aurelia.io/hub.html#/doc/persona/developer"
2) click on magnifying glass to search for a topic
3) in the search textbox, type "singleton"
4) click on the topic "Object Lifetime, Child Containers and Default Behavior"
5) click anywhere in the first paragraph (it is probably not necessary to be this specific)
6) click the menu Back link
7) click on any menu items

Result:
Nothing happens.  Also if you click on "Send us your Feedback", nothing happens ( lol ).  The app at this point seems quite confused.

Expect:
Normal navigation to occur.

**Comment by EisenbergEffect** [comment]
There are a few nav bugs we are working on. This seems similar to what
we've observed.

**Comment by Alexander-Taran** [comment]
maybe, can be closed

**Comment by dkent600** [comment]
With the new documentation site, I can't find a persona/developer page.  But trying the steps from any other arbitrary page works OK.

**Comment by Alexander-Taran** [comment]
@dkent600 you can close it, btw (-:

**Comment by EisenbergEffect** [comment]
we removed the personas for now

**Comment by dkent600** [comment]
@Alexander-Taran 

> you can close it, btw (-:

Thank you, I just don't want to presume too much about your processes....

**Comment by Alexander-Taran** [comment]
Not my process, I'm just helping out a bit.
But it's your issue. You can do whatever you want with it (-:
