### ISSUE TITLE
the 

### ISSUE THREAD

**Issue by dkent600** [aurelia/documentation#234]
The Logging docs given [here](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/app-configuration-and-startup/10) don't work when put into code.

This appears to be caused, in the code, by the syntax in the aurelia-framework.d.ts:  `export const [xyz] : [anyType]`

The following code *does* work:

```
import * as LogManager from "aurelia-logging";
```

usage:

```
var logger = LogManager.getLogger('MyClassName');
...
logger.debug('a debug message..');
```

(thanks to Paolo Furini @nexbit)

**Comment by EisenbergEffect** [comment]
Can you make a recommendation on how to fix the d.ts file? The code does technically work fine and is a supported feature of ES 2015 modules. It seems that TypeScript isn't understanding that or our dts is incorrect. How should we address this?

**Comment by dkent600** [comment]
@EisenbergEffect Let me investigate...

**Comment by dkent600** [comment]
@EisenbergEffect I just retested this and find that this may have been a user error on my part:  At the time I may have been trying to instantiate LogManager.  At least, that is my best guess as to why the problem has disappeared.

**Comment by EisenbergEffect** [comment]
Great. Thanks for the followup!
