### ISSUE TITLE
persist selection of typescript or ESNext, ES2015

### ISSUE THREAD

**Issue by dkent600** [aurelia/documentation#235]
It would be nice if the Hub would persist in the Url the selection of Typescript, ESNext, or ES2015.  I frequently forget to reselect TypeScript, which is not the default.

**Comment by EisenbergEffect** [comment]
@joelcoxokc Looks like a regression. Please address asap.

**Comment by Gheoan** [comment]
If I recall correctly the choice was not persistent even in the old docs (before hub).

**Comment by EisenbergEffect** [comment]
It absolutely should have been. There may have been a bug introduced at one time. Perhaps it went unnoticed.

**Comment by EisenbergEffect** [comment]
Please make sure that a person's selection of programming languages persists across browser refreshes. It does for me, but please check several browsers to be sure.

**Comment by Alexander-Taran** [comment]
can be closed

**Comment by dkent600** [comment]
Looks good
