### ISSUE TITLE
Document matcher.bind?

### ISSUE THREAD

**Issue by oscarcs** [aurelia/documentation#237]
There doesn't appear to be any easily-accessible documentation on using matcher.bind (with `<select>`s etc.) apart from [here](https://stackoverflow.com/questions/33920610/binding-a-select-to-an-array-of-objects-in-aurelia-and-matching-on-id). 

Maybe this should be in the main docs? It seems this would be a _reasonably_ common use case.

**Comment by EisenbergEffect** [comment]
@jdanyow Please be sure to include this topic in the binding docs you are working on.
