### ISSUE TITLE
HUB word is not associated with Documentation

### ISSUE THREAD

**Issue by Ma3yTa** [aurelia/documentation#239]
https://s31.postimg.org/6ytr0fwe3/wp_ss_20160709_0002.png

**Comment by Gheoan** [comment]
This issue is about people going to aurelia.io and not finding the docs and should be reopended.
My suggestion is to replace "hub" with "docs" until the hub is expanded to contain more then docs.

**Comment by EisenbergEffect** [comment]
There is a new web site design being worked on and rolling out in the next few weeks. Hub is about more than docs. Additional features are rolling out there as well.
