### ISSUE TITLE
HUB on Android browser

### ISSUE THREAD

**Issue by guidorice** [aurelia/documentation#242]
Hi, would it be possible to fix the HUB documentation to be usable on smaller screens? This screenshot is from Android 6.0.1 1080 x 1920 pixels (~445 ppi). It is not possible to hide the nav-bar on the left, and also the UI  is not zoomable to make it smaller (only larger)

![aurelia-hub-on-android](https://cloud.githubusercontent.com/assets/766758/16735154/546b08d2-4745-11e6-8db4-f371678f4b45.png)

**Comment by EisenbergEffect** [comment]
Closing this as a duplicate. We're already working on a mobile update.

**Comment by guidorice** [comment]
OK cool, thanks Rob. The HUB is a great resource.
