### ISSUE TITLE
Signal Demo not working?

### ISSUE THREAD

**Issue by guivr** [aurelia/documentation#243]
[Singal Demo](http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-binding-behaviors) 
don't appear to be working, wehn I click the 'Signal' button, nothing happens.

Is this normal?

**Comment by guivr** [comment]
Refreshed the page and worked

**Comment by EisenbergEffect** [comment]
Perhaps there was a temporary network issue?
