### ISSUE TITLE
Unexpected grave accent at 'HTML Behaviors Introduction > Global Resources > main' code

### ISSUE THREAD

**Issue by guivr** [aurelia/documentation#244]
There's a typing error on ['main' code example](http://aurelia.io/hub.html#/doc/article/aurelia/templating/latest/templating-html-behaviors-introduction/5) on line 5, which contains an unexpected grave accent after custom-element declaration.

I believe

('custom-element`, 'another-directory/custom-attribute');

should be

`('custom-element', 'another-directory/custom-attribute');`

**Comment by EisenbergEffect** [comment]
Got it. Thanks!
