### ISSUE TITLE
Aurelia - Hub - Unable to view the page content on mobile

### ISSUE THREAD

**Issue by HariharanS** [aurelia/documentation#245]
![img_5114 1](https://cloud.githubusercontent.com/assets/1931027/16750621/67e00350-4816-11e6-9993-2761223c7f4a.PNG)

I have attached a screenshot from my mobile. Unable to view the page content from either Safari or Chrome on my iPhone. 
The menu takes up the whole page (appears to be in the foreground) and the page content is hidden in the background.

**Comment by EisenbergEffect** [comment]
Yes, we have this tracked already. Closing as a duplicate.
