### ISSUE TITLE
The vertical scrollbar will disappear after dbclick on the aurelia.io doc page.

### ISSUE THREAD

**Issue by xiwc** [aurelia/documentation#246]
eg: http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/cheat-sheet/9

**Comment by EisenbergEffect** [comment]
@joelcoxokc Ping.

**Comment by EisenbergEffect** [comment]
@xiwc Can you provide some more details? I can't reproduce the problem.

**Comment by xiwc** [comment]
![image](https://cloud.githubusercontent.com/assets/8816203/16791216/4a8bec22-48ef-11e6-8784-2b10fcd7a689.png)


![image](https://cloud.githubusercontent.com/assets/8816203/16791326/6b8f305e-48f0-11e6-9a63-306f090a93ec.png)

**Comment by EisenbergEffect** [comment]
That's not really the information I'm looking for because we can't even reproduce the bug. I need to know:

* What operating system are you on?
* What browser and version are you using?
* What are the exact steps that cause the bug?

**Comment by xiwc** [comment]
@EisenbergEffect 
![image](https://cloud.githubusercontent.com/assets/8816203/16825695/73064f98-49a9-11e6-994e-fa96e29c1c2a.png)
![image](https://cloud.githubusercontent.com/assets/8816203/16825702/7c3959a2-49a9-11e6-811c-4aab991bd334.png)

steps:
1. open URL: http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/technical-benefits/8
2. dbclick any word on the main content body
3. then it will reproduce.

**Comment by xiwc** [comment]
@EisenbergEffect  
I have found the real reason: it's not compatible with my google chrome plugin(有道词典). It will be normal if turning off this plugin.

Sorry for my trouble.
