### ISSUE TITLE
Search on documentation should search content

### ISSUE THREAD

**Issue by jsobell** [aurelia/documentation#247]
Currently, searching for something like 'radio button' returns nothing. When users are looking for assistance they don't know which section to look under, and with about thirty subsections it's daft to expect them to search each one individually.
If necessary, add an option for 'search all content', but as-is it's unfortunately not very usable.

**Comment by EisenbergEffect** [comment]
I think our search indexing is missing headings that are less than h2. That's probably why some things aren't coming up. We'll investigate.

**Comment by Alexander-Taran** [comment]
can be closed

**Comment by EisenbergEffect** [comment]
should be fixed
