### ISSUE TITLE
New doc, not really very helpfull

### ISSUE THREAD

**Issue by fractalf** [aurelia/documentation#249]
![image](https://cloud.githubusercontent.com/assets/5707457/17077693/94e75ca6-50d9-11e6-8b84-26a6b63e0ed8.jpg)

this is what i get when trying to read some docs on an ipad2 with chrome. Gui is really bad and the search dont give me anything.

Please, put a link for the old docs somewhere?

**Comment by EisenbergEffect** [comment]
Mobile fix is coming this week.
