### ISSUE TITLE
Clarify if "detached" is fired before or after removal from the DOM

### ISSUE THREAD

**Issue by wichert** [aurelia/documentation#250]
Currently the documentation says "At some point in the future, the component may be removed from the DOM. If/When this happens, and if the view-model has a detached callback, this is when it will be invoked.". From that it is not clear if detached is fired just before, or just after the component is removed form the DOM.

**Comment by EisenbergEffect** [comment]
It is fired after removal from the dom. Would you be interested in submitting a PR to update the document with this clarification?

**Comment by Alexander-Taran** [comment]
please review pr to docs about detached()
