### ISSUE TITLE
Clicking the search icon does not focus the search input

### ISSUE THREAD

**Issue by gheoan** [aurelia/documentation#252]
**I'm submitting a bug report**

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Browser:**
  Chrome 52

**Current behavior:**

Clicking the search icon does not focus the search input.

**Expected/desired behavior:**
- **What is the expected behavior?**

Clicking the search icon should focus the search input.

**Comment by mkultra-z** [comment]
+1! I know its small but this is so frustrating.

- Operating System:
MacOS 10.12.5

- Browser:
Chrome 59

**Comment by EisenbergEffect** [comment]
We're working on an entirely new site and docs. In the new implementation, we've fixed this problem :)

**Comment by mkultra-z** [comment]
🙌  Will it be google indexable? and the api more descriptive? This would be awesome.. 
beta.docs.aurelia.io please!

**Comment by EisenbergEffect** [comment]
Yes, it will be indexable. The descriptive part will come over time. We are
renewing our effort in this area.

**Comment by gheoan** [comment]
This is fixed on the new site.
