### ISSUE TITLE
Dicsussion of contexual template binding items is hard to find

### ISSUE THREAD

**Issue by dkent600** [aurelia/documentation#256]
Contextual template binding items (seen below) should be in their own section, or else in the Templating Basics section, under the top level Templating topic.

Contextual items available inside a repeat template:
• $index  - The index of the item in the array.
• $first  - True if the item is the first item in the array.
• $last  - True if the item is the last item in the array.
• $even  - True if the item has an even numbered index.
• $odd  - True if the item has an odd numbered index

**Comment by EisenbergEffect** [comment]
Closing this as a duplicate. Would love a PR to the docs to add this :)
