### ISSUE TITLE
Contact Manager - Building Out the Contact Detail Screen

### ISSUE THREAD

**Issue by beatsm** [aurelia/documentation#259]
The html is for contact-detail.html but the documentation states to add it to the app.html

![image](https://cloud.githubusercontent.com/assets/3408087/17251060/0d7e3b66-559f-11e6-85d7-5b402f6da4af.png)

**Comment by Gheoan** [comment]
Will be fixed by https://github.com/aurelia/framework/pull/501.

**Comment by EisenbergEffect** [comment]
Fixed.
