### ISSUE TITLE
contact manager tutorial contradicts itself

### ISSUE THREAD

**Issue by xenoterracide** [aurelia/documentation#261]
> There are two bundles defined by default: app-bundle.js, which contains your code and vendor-bundle.js which contains all 3rd party libraries. We need to add a new items to the dependencies array of the app-bundle.js bundle. Add the following two entries for jQuery and Bootstrap:

>For now, just know that this causes jQuery, Bootstrap and all necessary CSS to be included in the vendor bundle and makes it reachable through the module system.

so it tells us to add it to app-bundle and then says it will be included in vendor bundle

**Comment by EisenbergEffect** [comment]
We had a typo. I think we've got that fixed now. Sorry about that!
