### ISSUE TITLE
All release notes in one place

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/documentation#262]
Every time I update the Aurelia libs, I try to find release notes to check for any (breaking) changes to inform testing before rolling it out. However, it's not exactly simple to find release notes for everything that changes when upgrading (e.g.) from RC1 to 1.0.0. There's a changelog (which is not exactly the same) for the release of each library on Github, and there's (sometimes) a higher-level discription and / or a masterlist of changelogs on blog.durandal.io.

Some consistency in this would be very much appreciated. Perhaps all the changelogs could be continuously aggregated on the hub? With some higher level explanation for major changes, if at all possible. And perhaps a feed of this? That would be ideal!

**Comment by EisenbergEffect** [comment]
There aren't any planned breaking changes for a long time, so I don't think you'll have to worry too much about that.

We'll be aggregating the changelog on the blog as usually. That content is directly taken from the change log generated by our release process and is the same content that is published in the release notes.

I'll leave this open to see if we can do something more in the future. It's not a top priority now. If it's important to you, please consider contributing by building a solution we can use.

**Comment by RomkeVdMeulen** [comment]
I didn't see an aggregated changelog on the [1.0.0 announcement](http://blog.durandal.io/2016/07/27/aurelia-1-0-is-here/). Will that be coming at some point?

**Comment by EisenbergEffect** [comment]
You are right. We didn't have one there. I don't think there were any breaking changes, just bug fixes and a couple of new features. We hadn't planned to generate a list but we could look at putting one together.
