### ISSUE TITLE
Contact Manager - Using Types in ES2015 example for app.js

### ISSUE THREAD

**Issue by dlo83** [aurelia/documentation#263]
**I'm submitting a bug report**

* **Library Version:**
1.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
5.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17

**Current behavior:**
In the app.js example found [here](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/contact-manager-tutorial/4),  types are in use even in an ES2015 example.

**Expected/desired behavior:**
Should display code in a loosely typed manner.

**Comment by EisenbergEffect** [comment]
Closing this as a duplicate since we've got this tracked as a bug in our language picker that occurs in that article.
