### ISSUE TITLE
CSS render error: grey text on grey background in Chromium

### ISSUE THREAD

**Issue by COLABORATI** [aurelia/documentation#265]
There is some problem with the documentation css: it renders grey text on grey background in chromium browser, what is barely readable. Please fix this to show high contrast so people can actually read the docs, thank you! 

![2016-08-08_aurelia-docs-grey-grey](https://cloud.githubusercontent.com/assets/6514273/17478548/ea6a630e-5d6c-11e6-95c9-5eec896fd40a.png)

**Comment by EisenbergEffect** [comment]
@scriswell How hard would it be to fix this?

**Comment by Alexander-Taran** [comment]
can be closed
