### ISSUE TITLE
HTML display of documentation does not seem to agree with GitHub Markdown

### ISSUE THREAD

**Issue by JMerrill** [aurelia/documentation#268]
I'm going through the Quick Start (excellent, btw). Using both Edge and Chrome, there is a snippet (search for "did you notice")

Second, did you notice the (code syntax marker blob with nothing in it)  syntax?

I wanted to fix this, so I looked at it in the .md source. I found this (line 257 of quick-start.md) [using blockquote so the back-tick isn't treated as code syntax marker]

>     Second, did you notice the `\${heading}` syntax?

The GitHub online markdown editor renders this as

Did you notice the \${heading} syntax?

with the code-syntax blob around \${heading}. So in theory removing the \ would make it correct; but I can't explain why there's nothing in the code-syntax blob as the markdown is now. Can you?

**Comment by EisenbergEffect** [comment]
We had a bug in the content which we did fix. If you are curious about the need for `\$` it is because our documents are actually passed through the aurelia view compiler so if we omitted the `\` it would think we were trying to databind to the `heading` property.
