### ISSUE TITLE
Typos in Quick Start documentation

### ISSUE THREAD

**Issue by jwatkin** [aurelia/documentation#269]
Here are some possible typos on this page:
http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/quick-start/6

**1**
“Second, did you notice the **(there’s an empty gray box here, one character wide)** syntax?”

**2**
Shouldn’t this, “…template **sting** syntax as shown…”, be this, “…template **string** syntax as shown…”?

**3**
I don’t understand the following. Should “addTodo” be “removeTodo”?
“Notice that the removeTodo is still in scope. Just like in TypeScript, inside a loop, you still have access to the variable in the outer block. This allows us to call the **addTodo** method on the App class, passing in the particular Todo instance that we want to remove.”

**4**
On this page:
http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/quick-start/2
Shouldn't this, "Aurelia also **support** module-based build systems like Webpack.", be this, "Aurelia also **supports** module-based build systems like Webpack."

**Comment by Hannesver** [comment]
It also says `SystemJS.import('aurelia-bootstrapper');`, while it is `System.import('aurelia-bootstrapper');`

**Comment by EisenbergEffect** [comment]
We've got them fixed. (FYI SystemJS is a safe access over top System, since System is no longer a standard.)
