### ISSUE TITLE
incorrect filenames in contact manager tutorial

### ISSUE THREAD

**Issue by dsm054** [aurelia/documentation#271]
**I'm submitting a bug report**
----

First, in http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/contact-manager-tutorial/6, it says

> On that note, create a contact-list.html file and use the following code for the view:

but the filename in the code box says `no-selection.html` instead.  This can lead to a mysterious `vendor-bundle.js:3675 Uncaught TypeError: h.load is not a function` error..

Second, in http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/contact-manager-tutorial/7, it says `app.html` in the code box, but it looks to me like it should be `contact-detail.html` instead.

**Comment by EisenbergEffect** [comment]
Got it fixed a little while back. Sorry we didn't update here!
