### ISSUE TITLE
A couple of typos in documentation

### ISSUE THREAD

**Issue by gamtiq** [aurelia/documentation#273]
There are the following typos in documentation:
* In [Creating A New Aurelia Project](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/contact-manager-tutorial/2) section of "Contact Manager Tutorial":
> Hit enter to *accpet* the default "yes".

* In code for "Basic HTTP Interceptors" inside [aurelia-http-client](http://aurelia.io/hub.html#/doc/article/aurelia/fetch-client/latest/http-services/3) section of "HTTP Services" page:
```js
let client = new HttpClient();
  .configure(x => {
```

* In [Creating Components](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/creating-components/1) there are missed and improper periods in the following sentence:

> Those are the defaults, but you can always be explicit about the binding direction by using .one-way, two-way or .one-time in place of .bind. (.one-time renders the initial value of the property but does not perform synchronization thereafter, making it a nice memory and performance gain for data you know will not change.)

* In [Making an HTML Behavior Available in a View](http://aurelia.io/hub.html#/doc/article/aurelia/templating/latest/templating-html-behaviors-introduction/4) section of [Templating: HTML Behaviors Introduction](http://aurelia.io/hub.html#/doc/article/aurelia/templating/latest/templating-html-behaviors-introduction/):

> There is one exception to this rule*, though.* Aurelia provides for "HTML-only Custom Elements*."*

It seems this sentence should be as the following:
> There is one exception to this rule, though, Aurelia provides for "HTML-only Custom Elements".

**Comment by EisenbergEffect** [comment]
@gamtiq How about submitting a PR to address these issues? All our docs are on github. You will find them in the repo related to the topic, under a docs folder. It's a great way to contribute to the project.

**Comment by gamtiq** [comment]
@EisenbergEffect I'll try to make changes in documentation during the week.

**Comment by gamtiq** [comment]
The following typo has been fixed already.
> Hit enter to accpet the default "yes".
