### ISSUE TITLE
Can't change between ES 2016 and TypeScript in examples

### ISSUE THREAD

**Issue by feardarkness** [aurelia/documentation#276]
Hi, when i try to change between ECMA 2016 and typescript in docs nothing happens. 

url: http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/contact-manager-tutorial/4

Chromium Versión 51.0.2704.79 Ubuntu 16.04 (64-bit)
Firefox 48.0

**Comment by EisenbergEffect** [comment]
It does work correctly for some of the code samples, but others don't. We may have some incorrect configuration for those languages in those cases. We'll check it out.

**Comment by Alexander-Taran** [comment]
fixed in new docs
can be closed
