### ISSUE TITLE
bindable properties must be all lowercase

### ISSUE THREAD

**Issue by dpix** [aurelia/documentation#278]
if you try to create bindable property on a custom element like so: 

``` html
<search locationType="location"></search>
```

locationType cannot be bound to because the dom will render the property name all lower case like `locationtype`

I ran into this issue today, and although it seemed obvious as soon as I realised I could not use camel casing, it would be nice if this was explicit in the documentation (I couldn't find it anywhere) as I'm sure I'm not the only one who will trip over this

**Comment by EisenbergEffect** [comment]
@AshleyGrant Didn't we have this in the documentation somewhere?

**Comment by Alexander-Taran** [comment]
http://aurelia.io/docs/fundamentals/cheat-sheet#custom-elements
Custom Element Variable Binding 

it is documented.. but.. 

could be closed
