### ISSUE TITLE
non-working example code 

### ISSUE THREAD

**Issue by dissolve** [aurelia/documentation#279]
in router configuration -> pipelines -> An Authorize Step  (ES Next)
http://aurelia.io/hub.html#/doc/article/aurelia/router/latest/router-configuration/8 

This code gets and error of "step is not defined"

It looks like the docs are missing something like 

`var step = new AuthorizeStep
`

**Comment by EisenbergEffect** [comment]
You are right! Would you care to make a PR to fix that? The doc is in the router repo. It should be a quick fix and an nice way to contribute.
