### ISSUE TITLE
Create an ES6 style guide

### ISSUE THREAD

**Issue by PWKad** [aurelia/documentation#28]
Create a style guide as a guideline for contribution as well as a guide for the community to follow when writing their ES6 code.

**Comment by PWKad** [comment]
Also need to incorporate something like https://www.npmjs.com/package/gulp-jscs into the build process to enforce code styling.

**Comment by PWKad** [comment]
Here's a sample of something we could add to the style guide - 

# Modules:

### Modules should follow the following pattern - 

```
// All imports at the top
import {Something} from 'something';

// All class and function definitions in the middle
class Session {
  // Inject dependencies first
  static inject () { return [Something] }
  // Constructor directly next
  constructor(something) {
    // All variables defined directly on this
    this.currentUser = new User();
    // All public functions to be exposed defined directly on this
    this.setCurrentUser = function () {  };
  }
  // All life-cycle events defined outside of constructor
  activate() {
    console.log(this.currentUser);
  };
}

// All exports at the end
export {
  Session
}
```

**Comment by jdanyow** [comment]
@EisenbergEffect found the [airbnb style guide](https://github.com/airbnb/javascript/tree/es6)

discussion
:point_up: [April 3 2015 3:24 PM](https://gitter.im/aurelia?at=551ee8e11f582983259f339f)
:point_up: [April 6 2015 11:42 AM](https://gitter.im/aurelia?at=5522a94f6e3562b64f5367e9)

**Comment by EisenbergEffect** [comment]
I'm thinking we should fork that to use it as a starting point and then fix up the stuff we really don't like.

**Comment by EisenbergEffect** [comment]
We've now set up linting across repos.
