### ISSUE TITLE
Duplicate topic indices for Setup & Bundling on Hub

### ISSUE THREAD

**Issue by devanp92** [aurelia/documentation#281]
**I'm submitting a bug report**
- **Browser:**
  all

**Current behavior:**

<img width="1280" alt="chrome_2016-09-16_14-17-45" src="https://cloud.githubusercontent.com/assets/4533277/18596679/68432f3a-7c18-11e6-9cf6-b52573c82047.png">

**Comment by EisenbergEffect** [comment]
They are actually different. It's just that it's not clear from that particular view. We'll look into improving that.

**Comment by Alexander-Taran** [comment]
old hub is gone

can be closed
