### ISSUE TITLE
Text overflows on Browser resize for Validation Doc

### ISSUE THREAD

**Issue by devanp92** [aurelia/documentation#282]
**I'm submitting a bug report**
- Browser: all 

Browser size: 1077px x 1050px
**Current behavior:**
![image](https://cloud.githubusercontent.com/assets/4533277/18596734/b04a8dd2-7c18-11e6-81c0-fd5e9dab008a.png)

**Comment by EisenbergEffect** [comment]
Looks like our CSS should be switching to a single column but isn't. Thanks for the heads up!

**Comment by Alexander-Taran** [comment]
old hub issue

can be closed
