### ISSUE TITLE
Contact Manager could use clarification

### ISSUE THREAD

**Issue by jbrinkman** [aurelia/documentation#283]
**I'm submitting a feature request**

* **Browser:**
All

* **Language:**
TypeScript 

**Current behavior:**
I am currently working through the getting started documentation.  After finishing the Quick Start section, the next section I am presented with is the Contact Manager example.  The beginning of the documentation states:

> Now that you've got the basics down, you need to learn how to use the CLI

I assume that this means that this tutorial will walk me through using the CLI to create, build and run an Aurelia app.  The instructions are fairly clear on how to install/create the new contact-manager application, but when it gets to the "Building Out the Default Route" it does a quick hand-wave and says 

> If you run the application now, you'll see a blank screen 

This statement is not helpful at all.  As a tutorial purporting to teach me how to use the CLI, this tutorial fails in that goal since it is left up to the reader to go and find out how to run the application.  In the quick start it was just a matter or starting up the web server and then browsing to the webpage in the browser.  If I follow that same process in this tutorial I just get an error stating that the vendor-bundle.js could not be found. After doing some research on stack-overflow, I inferred that there was a build step involved and after further investigation of the docs, I found an article on the CLI which finally got me past this step.  What should have been a 10 second exercise became a 10 minute process testing my ability to use Google and use deductive reasoning.  Getting started docs should be easier than this.

**Expected behavior:**
The documentation should include a brief description of how to build and run the application and as a bonus should link to the CLI documentation.

**Comment by EisenbergEffect** [comment]
Just confirmed that the docs do explain how to run the app earlier on.
