### ISSUE TITLE
Aurelia CLI docs should explain how to run ASP.NET Core projects

### ISSUE THREAD

**Issue by LarsKemmann** [aurelia/documentation#285]
**I'm submitting a bug report**
- **Language:**
  ESNext

**Current behavior:**
Executing `au run` returns a `404 Not Found` error at `http://localhost:9000/` together with the message:

> Cannot GET /

Running the ASP.NET Core project works fine, once `Startup.Configure` is modified to include the following:

```
app.UseStaticFiles();
```

However, I have to navigate to `http://locahost:{port}/index.html`, I can't just navigate to `http://localhost:{port}/`.

**Expected/desired behavior:**
I don't know what The Right Way(TM) is for accomplishing the above (I'm still new to this), but I would like the Aurelia HUB documentation to call this out in the instructions for getting started with the Aurelia CLI.

**Comment by LarsKemmann** [comment]
This issue is helpful as well: https://github.com/aurelia/cli/issues/285

**Comment by EisenbergEffect** [comment]
@LarsKemmann Would you be interested in submitting a PR to the CLI documentation to help asp.net Core developers with this in the future? The documentation for the cli is in the framework repo, under the docs folder in the en-US sub folder.

**Comment by LarsKemmann** [comment]
@EisenbergEffect Yes, I'd be happy to.

**Comment by spapaseit** [comment]
Nice job @LarsKemmann, thank you very much! One small addition though, I followed your instructions and still got a 404. 

I solved it by pointing all `output` settings in `aurelia.json` to `wwwroot`, so from:

```
...
"output": "scripts"
...
```

to:

```
...
"output": "wwwroot/scripts" 
...
```

**Comment by RichiCoder1** [comment]
^ That. In addition, one thing that the starter kits (and I think CLI) does that isn't mentioned here is that the former recommends stopping VS TS compilation entirely `<TypeScriptCompileBlocked>True</TypeScriptCompileBlocked>`.

**Comment by Alexander-Taran** [comment]
@LarsKemmann let's close this (-:

**Comment by LarsKemmann** [comment]
> @LarsKemmann let's close this (-:

Please feel free. 😊

**Comment by LarsKemmann** [comment]
Huh, look at that! I didn't realize I could close my own issues. 😁
