### ISSUE TITLE
Aurelia Hub UI

### ISSUE THREAD

**Issue by amourrashid** [aurelia/documentation#289]
The Aurelia Hub UI is one of the best for building business applications. Why not offer it to the aurelia community.
  I think this would be a very good starting point for aurelia developers.
The current skeleton application is not fit for complex application.
I remember Rob used to show a sample app before his journey to angular. Where is that Rob?

**Comment by EisenbergEffect** [comment]
The hub codebase would need to be cleaned up a lot before we could share it. I'm actually working on that a little each day now.

There are various samples around. I'm not sure which one you are referring to.
