### ISSUE TITLE
Not a bug but a suggestion for improvement

### ISSUE THREAD

**Issue by thepowderriverfarrier** [aurelia/documentation#290]
* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17

* **Browser:**
all 

* **Language:**
all 

**Current behavior:**
On line viewing of documentation.

**Expected/desired behavior:**
It would greatly expedite learning Aurelia if I could easily print out the online documentation
for carrying it with me to read when time allows.

* **What is the motivation / use case for changing the behavior?**
I know one of the Angular2 developers and I'd like to discuss Aurelia with him.

**Comment by EisenbergEffect** [comment]
I believe we have this tracked, so closing as a duplicate.

**Comment by thepowderriverfarrier** [comment]
Thanks.  Is there a link to the printable version of the documentation? 

    On Thursday, October 6, 2016 10:22 AM, Rob Eisenberg <notifications@github.com> wrote:
 

 I believe we have this tracked, so closing as a duplicate.—

**Comment by EisenbergEffect** [comment]
No we don't have a printable version. What I meant is that we are tracking that as a feature we want to implement in another Github issue already.
