### ISSUE TITLE
Please document replace and trigger boolean options of redirectoroute

### ISSUE THREAD

**Issue by forestmarie** [aurelia/documentation#292]
**I'm submitting a feature request**

I can find no official documentation on these features.  I learned about them during Rob's workshop.  

this.router.navigateToRoute('some router', { route parameters... }, { trigger: true/false, replace: true/false }); 

Please provide coverage on these with some example use cases on using trigger and replace.

Thanks!

**Comment by EisenbergEffect** [comment]
@AshleyGrant I think you said something the other day about documenting the router. I think we need a new document in addition to our configuration document that covers some of the router APIs used during the course of an app. That would be a good place to document the `navigate` APIs and include details on the settings that @forestmarie mentions. You up for that?

**Comment by AshleyGrant** [comment]
I can do it, but I'm definitely not currently a router expert. You can assign me though.

**Comment by EisenbergEffect** [comment]
If we just get a start with a few items in it we can take PRs to expand it easily in the future.

**Comment by Alexander-Taran** [comment]
Router is documented by now

can be closed

**Comment by AshleyGrant** [comment]
I just want to say that I really appreciate the work @Alexander-Taran is doing by going through old issues. Thank you!
