### ISSUE TITLE
show more thorough example of implementing and then using a feature

### ISSUE THREAD

**Issue by lmj0011** [aurelia/documentation#293]
**I'm submitting a feature request**
- **Language:**
  all 

<hr>

http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/app-configuration-and-startup/6

A gistrun of this being put into practical use would be helpful. I'm not sure how I would reference the `my-feature` in my app.

``` js
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .feature('my-feature');

  aurelia.start().then(() => aurelia.setRoot());
}
```

**Comment by Alexander-Taran** [comment]
hub is dead
http://aurelia.io/docs/fundamentals/app-configuration-and-startup#organizing-your-app-with-features
seems sufficient..

although I remember some discussions on index being required when `use.feature()` or is it relevant only for webpack?

maybe can be closed

**Comment by EisenbergEffect** [comment]
@jods4 What is the requirement for Aurelia features with Webpack? Is it to use the `PLATFORM.moduleName('folder/index');`? If so, I can add that to the docs. Let me know.

**Comment by jods4** [comment]
Features are module names loaded by Webpack, so they should be enclosed in `PLATFORM.moduleName`, yes.

Pitfall: Aurelia used to automatically append the `/index` but it won't work. When using Webpack, you have to add `/index` explicitely.
