### ISSUE TITLE
Validation section lists binding behavior that no longer exist

### ISSUE THREAD

**Issue by dkent600** [aurelia/documentation#295]
The "Validate Binding Behavior" section lists the following binding behaviors that appear to no longer exist:
```
& validateOnBlur: the DOM blur event triggers validation.
& validateOnChange: data entry that changes the model triggers validation.
& validateOnBlurOrChange: DOM blur or data entry triggers validation.
& validateManually: the binding is not validated automatically when the associated element is blurred or changed by the user.
```

**Comment by EisenbergEffect** [comment]
@jdanyow Can we update the docs to match?

**Comment by jdanyow** [comment]
@dkent600 - you may have an old build.  The binding behaviors do exist:
https://github.com/aurelia/validation/blob/master/src/validate-binding-behavior.ts

**Comment by dkent600** [comment]
I am using build 0.12.5, and when I try to use those bindings I get a javascript exception indicating they have not been registered.

**Comment by dkent600** [comment]
@jdanyow  OK, I was misusing jspm, I see the latest is 0.13.1
