### ISSUE TITLE
Validation doesn't document the Binding class used by registerBinding or unregisterBinding

### ISSUE THREAD

**Issue by dkent600** [aurelia/documentation#296]
Validation doesn't adequately document registerBinding and unregisterBinding methods on ValidationController, nor the Binding class that they take as a parameter.   There is a very minimal explanation of these methods in the API docs, but there is nothing for the Binding class, understanding of which is key to understanding how these methods can be used.  `Binding`, if it is in the in the search box at all, is too hard to find there amongst a jillion hits listed.  I didn't find it in the API sections for Binding, Templating nor Routing.

**Comment by dkent600** [comment]
I did just find a Binding as an *interface* in the API section under "Binding".  But honestly, I would have no idea how to supply that to registerBinding and unregisterBinding.

Would be great to have a better explanation for how registerBinding and unregisterBinding are meant to be used.

**Comment by EisenbergEffect** [comment]
The Binding interfaces comes from the aurelia-binding library. You don't usually do anything with it directly unless you are creating binding behaviors:http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-binding-behaviors/7 It's a structure that is created during view compilation. @jdanyow may have some thoughts on the register APIs.

**Comment by jdanyow** [comment]
these methods aren't heavily documented because devs don't use them directly, the validate binding behavior uses them.

**Comment by dkent600** [comment]
Would be sufficient to just state that in the docs.
