### ISSUE TITLE
Cheat sheet should list all DI resolvers and give an example of every one of them

### ISSUE THREAD

**Issue by dkent600** [aurelia/documentation#298]
The DI cheat sheet says that the following are _all_ the resolvers that exist, but they aren't.  

> Lazy - Injects a function for lazily evaluating the dependency. 
> ex. Lazy.of(HttpClient)
> All - Injects an array of all services registered with the provided key. 
> ex. All.of(Plugin)
> Optional - Injects an instance of a class only if it already exists in the container; null otherwise. 
> ex. Optional.of(LoggedInUser)

It would be very nice if we could a list of _all_ of the resolvers and also see an example of the use of _each_ of them.  

(I am trying to figure out how to use the Factory resolver, but can find nothing in the docs to indicate how one can use it to pass data to the constructor.)

Here are the missing resolvers, as listed in the DI Basics/Resolvers section:

> Parent - Skips starting dependency resolution from the current container and instead begins the lookup process on the parent container. 
> ex. Parent.of(MyCustomElement)
> Factory - Used to allow injecting dependencies, but also passing data to the constructor. 
> ex. Factory.of(CustomClass)
> NewInstance - Used to inject a new instance of a dependency, without regard for existing instances in the container. 
> ex. NewInstance.of(CustomClass).as(Another)

**Comment by Alexander-Taran** [comment]
done 
http://aurelia.io/docs/fundamentals/cheat-sheet#dependency-injection

can be closed
