### ISSUE TITLE
Validation.CustomRules.addRule example code looks wrong

### ISSUE THREAD

**Issue by dkent600** [aurelia/documentation#302]
In the section Validation.CustomRules.addRule when supplying parameters, does not make sense to me.

Why is the rule evaluation function like this:

`value >= config.min && value <= config.max` 

instead of like this:

`value >= min && value <= max`

Here is what the docs have:

```
ValidationRules.customRule(
  'integerRange',
  (value, obj, min, max) => value === null || value === undefined 
    || Number.isInteger(value) && value >= config.min && value <= config.max,
  `\${$displayName} must be an integer between \${$config.min} and \${$config.max}.`,
  (min, max) => ({ min, max }) 
);
```

**Comment by EisenbergEffect** [comment]
@jdanyow Can you take a look and PR a fix to the docs if there's an issue?

**Comment by jdanyow** [comment]
closing- we received and merged a PR that fixed this.
