### ISSUE TITLE
More beginner tutorials

### ISSUE THREAD

**Issue by con-ssc** [aurelia/documentation#303]
**I'm submitting a feature request**
In my opinion there are not enough beginner to intermediate level tutorials that work. I worked through the todo app but that is not enough knowledge to for example use multiple modules to use in one app. Also there was no information on how to put that app in place online and what files are necessary for it.
I also tried the contact-manager but that one didn't work very well.
So it would be nice to have more tutorials that explain on how to put an app together with different components and how to extend them other than the contact-manager tutorial. And maybe also in addition on how to implement 3rd party components like a grid from jquery mobile or any other component to move from a html only version of it to a template version.

**Comment by EisenbergEffect** [comment]
Please tell us what "did not work" about the contact manager. We haven't heard this.

**Comment by EisenbergEffect** [comment]
Closing since there's no followup from OP on what didn't work after over 3 weeks.
