### ISSUE TITLE
Custom binding behaviors section doesn't describe the arguments to bind and unbind

### ISSUE THREAD

**Issue by dkent600** [aurelia/documentation#304]
The "Custom binding behaviors" section doesn't describe the arguments to the `bind` and `unbind` methods.

The arguments are `binding` and `scope`, but there is no description of what these arguments refer to.  In the TypeScript view there are no types given that would yield a clue.

The lack of this documentation increases the initial challenge in creating a custom binding behavior.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you enhance the docs a bit with this information?
