### ISSUE TITLE
updateSource, updateTarget and callSource are documented as properties instead of methods

### ISSUE THREAD

**Issue by dkent600** [aurelia/documentation#305]
In the API docs page for `Binding`, `updateSource`, `updateTarget` and `callSource` are documented as properties instead of methods.  They are methods.

Would be nice to know what "Source" and "Target" refer to.  I would assume viewmodel and element, but would like to see it explicit in the docs.

(I might add (forgive me) that the purpose of  `callSource` is really not clear.)

**Comment by EisenbergEffect** [comment]
@jdanyow Can you take a look at the d.ts file for binding and see if all the type info is present?

**Comment by jdanyow** [comment]
Initially typedoc didn't work with the `updateSource?(value: any): void` style syntax so we had to use the `updateTarget?: (value: any) => void;` style. Seems to work now.
