### ISSUE TITLE
Feature request: Add cookbooks and recipes

### ISSUE THREAD

**Issue by aligneddev** [aurelia/documentation#308]
The Aurelia docs are great, but I struggled to find examples when I was building a quick demo app. I wasn't taking the time at the moment to dig real deep, so examples would have been nice. my code is here: https://github.com/logankd/JQueryToAurelia/tree/master/src/aurelia

I asked a few questions on StackOverflow, that were quickly answered by @AshleyGrant (thank you!).
http://stackoverflow.com/questions/40390370/passing-an-object-with-aurelia-router-navigate-to-a-view
http://stackoverflow.com/questions/40348535/organize-by-folder-in-aurelia

A Master Details example with dialog or using the router would be a good starting example.

Angular 2 has some nice recipes in there cookbook.
https://angular.io/docs/ts/latest/cookbook/component-communication.html#!#parent-to-child

Ward Bell talks about their documentation and had a lot of good ideas.
http://dotnetrocks.com/?show=1366

Thank you!

**Comment by Alexander-Taran** [comment]
We are gathering recipes @ https://github.com/aurelia-contrib/aurelia-getting-started/tree/master/guides

**Comment by aligneddev** [comment]
Great to hear!
