### ISSUE TITLE
router-view swap-order attribute is not documented

### ISSUE THREAD

**Issue by dkent600** [aurelia/documentation#310]
I am trying to get animations working, for between routes and for showing and hiding dialogs, and am having issues with both (using aurelia-animator-velocity v 1.0.1).

So I've been googling to find documentation about animation that might help me.  I have turned up documents alluding to using "swap-order" to improve how animations work, at least with respect to routing.  

The suggested code would supposedly look something like this:

`<router-view swap-order="with"></router-view>`

However, I can find no documentation of this feature in the aurelia hub documentation.  Searching for "swap-order" turns up nothing.  

When I dig around in the Aurelia code itself, I find stuff about ViewPortInstruction and "SwapStrategies".  Searching in the hub for "swap" turns up something in the API under "templating-router :: RouterView" referring to `viewPortInstruction`, but it really doesn't help beyond that.

**Comment by EisenbergEffect** [comment]
Would you be interested in submitting a PR?

**Comment by dkent600** [comment]
I would if I had any idea what it does.

**Comment by dkent600** [comment]
I may do the research to figure out what it swap-order does

**Comment by dkent600** [comment]
If you want I might also be able to work #314 in the same PR.  Being attributes of the same custom element (`router-view`) and side-by-side in the same document, it would be efficient to make the changes together.  What do you think?

**Comment by EisenbergEffect** [comment]
Sounds great!

**Comment by Alexander-Taran** [comment]
merged

maybe can be closed
