### ISSUE TITLE
Documentations should be indexable by search engines

### ISSUE THREAD

**Issue by larvanitis** [aurelia/documentation#312]
See this example [Google search for `aurelia binding` on offical site](https://www.google.com/?gws_rd=ssl#q=aurelia+binding+site:aurelia.io). The _hub_ pages should be there but they are not.

**Comment by EisenbergEffect** [comment]
Closing as a duplicate. As mentioned previously, we're tracking this and planning it pending our server-render implementation, which we are working on.
