### ISSUE TITLE
Search input field should be focus after clicking on the search icon

### ISSUE THREAD

**Issue by larvanitis** [aurelia/documentation#313]
**I'm submitting a bug report**

* **Browser:**
all

**Current behavior:**
On aurelia hub, when you click on the search icon (top right corner), the search sidebar opens but the focus is not on the input field.

**Expected/desired behavior:**
The input field should be focused the same way it is when you use the shortcut `Ctrl-Shift-P`.

* **What is the motivation / use case for changing the behavior?**
It is a major inconvenience when you use it multiple times a day.

**Comment by EisenbergEffect** [comment]
Closing as duplicate.
