### ISSUE TITLE
Routing=>Router Configuration=>Layouts section seems to be lacking information

### ISSUE THREAD

**Issue by dkent600** [aurelia/documentation#314]
The content in Routing=>Router Configuration=>Layouts section seems to be lacking some important and helpful information.  I find that the section is missing the following:

1. better description of what a "layout" is/does
2. code example of how to implement a layout view
3. more explicit description of the fact (I believe) that one can reference layouts in two places, on the `router-view` element and via the `configureRouter` method.

**Comment by Alexander-Taran** [comment]
seems fine: http://aurelia.io/docs/routing/configuration#layouts

can be closed
