### ISSUE TITLE
Router View Ports are sparsely documented

### ISSUE THREAD

**Issue by dkent600** [aurelia/documentation#317]
I find that Routing=>Router Configuration=>Rendering View Ports could use a little more information, primarily the definition of a view port.  What is a view port?

If desired, I can add this as part of the work I'm doing on #310 (_et al_).  It's all in one place.

**Comment by EisenbergEffect** [comment]
Fee free to add that. A "view port" just represents a place where a view model can be rendered. They map to router-views.

**Comment by dkent600** [comment]
Already wrote it up  :-)

**Comment by Alexander-Taran** [comment]
merged

can be closed
