### ISSUE TITLE
There is no API documentation for the Validation plugin under in the "Library"

### ISSUE THREAD

**Issue by dkent600** [aurelia/documentation#325]
There is no API documentation for the Validation plugin under in the "Library".  Completely empty.

**Comment by EisenbergEffect** [comment]
I believe we've got a fix for this merged. @jdanyow Is that correct? It just needs to be released, right?

**Comment by dkent600** [comment]
The validation documentation is still really flakey for me.

**Comment by Alexander-Taran** [comment]
can be closed
