### ISSUE TITLE
Mention restarting aurelia when installing NPM packages

### ISSUE THREAD

**Issue by brylie** [aurelia/documentation#326]
**I'm submitting a feature request**

* **Library Version:**
Doc HUB

**Current behavior:**
When working through the **Contact Manager Tutorial**, under **Building the Application Shell** the user is guided to install two NPM packages (Bootstrap and jQuery). After installing those packages the screen remains blank and a console error is given regarding the Bootstrap import failure.

**Expected/desired behavior:**
The instructions might mention, briefly, to restart aurelia if the page is still blank, after installing NPM packages.

* **What is the expected behavior?**
The NPM packages would work automatically when running aurelia with `au run --watch`, or the tutorial should mention it might be necessary to restart aurelia.

* **What is the motivation / use case for changing the behavior?**
The introductory tutorials are a critical path for onboarding new aurelia users. Any difficulties might throw a new user, possibly deterring them from continuing to study the framework. The onboarding path should be as smooth and explicit as possible.

**Comment by zewa666** [comment]
Wow that was definitely untouched for too long. @EisenbergEffect lets get the PR merged and the issue closed

**Comment by Alexander-Taran** [comment]
merged
can be closed
