### ISSUE TITLE
SEO friendly documentation (server-side rendering)

### ISSUE THREAD

**Issue by atsu85** [aurelia/documentation#328]
**I'm submitting a feature request**

* **Browser:**
all

**Current behavior:**
Currently Aurelia [hub](http://aurelia.io/hub.html)(documentation) isn't SEO friendly (google doesn't index it). As a result search engines, such as Google, won't find anything from that site.

**Expected/desired behavior:**
Search engines should be able to index and return search results from Aurelia Hub

* **What is the motivation / use case for changing the behavior?**
The most important reason against Aurelia for now (from my colleagues) is that You can't google Aurelia documentation (and it is difficult to find what You are searching for). If the hub would be rendered on server side, this would enable search engines to index it (would be nice showcase for [aurelia-pal-node](https://github.com/aurelia/pal-nodejs).

*I know there is an embedded searchbox, that is better than nothing, but not what people are used to nowadays. For example searching "lifecycle hook" from hub searchbox should match both singular form of "hook" (from the [The Route Screen Activation Lifecycle](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/cheat-sheet/7)) and plural form [The Component Lifecycle](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/creating-components/3), but for some reason the search returns only latter instead of both.*

**Comment by EisenbergEffect** [comment]
We're already got this tracked and the plan is to use our new server render to address this when it's ready.
