### ISSUE TITLE
Topic Index page repeating row

### ISSUE THREAD

**Issue by davidtimovski** [aurelia/documentation#329]
On the Topic Index page (for the role of Developer) there is a repeating row.

[http://aurelia.io/hub.html#/doc/persona/developer](http://aurelia.io/hub.html#/doc/persona/developer)

![capture](https://cloud.githubusercontent.com/assets/25406486/23480726/412595c6-fec9-11e6-8b6b-3ebdb6dd8e75.JPG)

**Comment by EisenbergEffect** [comment]
It's actually different items, they just have the same name. Not great as a content model, I agree.

**Comment by davidtimovski** [comment]
@EisenbergEffect Oh I didn't notice that. That's really confusing. Maybe it should be like:

Setup with Webpack | Bundling with Webpack
----------------------- | -------------------------
Setup with JSPM | Bundling with JSPM

**Comment by EisenbergEffect** [comment]
Totally agree. We need to get that fixed.

**Comment by Alexander-Taran** [comment]
hub moved to docs.
can be closed

**Comment by EisenbergEffect** [comment]
Yep. We changed the design of this significantly.
