### ISSUE TITLE
Router: When using pushState, a base tag may be necessary

### ISSUE THREAD

**Issue by jus101** [aurelia/documentation#33]
I have a pushState router with two routes set up like so:
```
{ route: "/organisations", moduleId: "modules/organisations/organisations"},
{ route: "/organisations/:org", moduleId: "modules/organisations/organisation”}
```
When I navigate to the second route, aurelia tries to load the view from /organisations/dist/modules/organisations/organisation.html (which 404s).

When I remove the pushState option - it works as expected (loads view from /dist/modules/organisations/organisation.html)

@EisenbergEffect suggested adding a base tag:
```
<base href="/" />
```

This fixes the issue. This is a reminder to include using a base tag in the docs if using pushState.

**Comment by mttmccb** [comment]
This does appear to be solving my problem, there anywhere else the baseURL needs to be defined, I think I've tried every combination...
