### ISSUE TITLE
Content-Projection pages error out - unable to navigate/read the docs

### ISSUE THREAD

**Issue by m-andrew-albright** [aurelia/documentation#330]
Navigating to the content-projection portion of the docs (http://aurelia.io/hub.html#/doc/article/aurelia/templating/latest/templating-content-projection) in all browsers is currently impossible.  I get this error:

![image](https://cloud.githubusercontent.com/assets/4950445/23852292/097a5180-07b5-11e7-85b2-daae6fe7e87e.png)

**Comment by EisenbergEffect** [comment]
We're aware. There appears to be a bug in the content formatting itself. We're looking into it.
