### ISSUE TITLE
Unclear where to go after reading the getting started

### ISSUE THREAD

**Issue by johot** [aurelia/documentation#331]
After reading through the "Quick start" document (http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/quick-start/7) it's not very clear for me where to continue reading.

In the last section it says "_There's so much more to learn and do! We hope you'll continue on to our "Contact Manager" tutorial to learn how to use the Aurelia CLI to get setup with a..._"

but there is no "Continue" link or button at the end of the page, you will have to understand that you need to click the back button in the panel to the left and then select the "Contact Manager". I think this needs to be more clear. Add a button at the end of each article that says "Continue" or something like that. If you read too fast you will miss this information and don't know where to continue learning Aurelia.

Thanks!

**Comment by EisenbergEffect** [comment]
Thanks for the feedback. We're building a new version of our developer hub where it will be easy to add features to improve this.

**Comment by Alexander-Taran** [comment]
hub is dead..
