### ISSUE TITLE
Aurelia.io documentation never shows up when "googling"

### ISSUE THREAD

**Issue by johot** [aurelia/documentation#332]
This is a big issue, when googling I will never ever find links to the aurelia.io documentation just a bunch of old blogs with possibly the wrong information, this is not good for the Aurelia project. It makes it hard for beginners to find the correct information.

I am guessing this is a problem because the documentation hub is a big SPA and google can't index it properly? Does any plan to fix this exist? Maybe the documentation needs to be static pages instead of a SPA (worst case scenario)...?

**Comment by EisenbergEffect** [comment]
Thanks for the feedback. We're building a new version of our developer hub where it will be easy to add features to improve this.
