### ISSUE TITLE
templating-content-projection area not working

### ISSUE THREAD

**Issue by gbreeze** [aurelia/documentation#335]
http://aurelia.io/hub.html#/doc/article/aurelia/templating/latest/templating-content-projection

Tested on Opera, Edge

![image](https://cloud.githubusercontent.com/assets/1906169/24567528/719b8e2a-165e-11e7-9333-7662deaa2163.png)

**Comment by EisenbergEffect** [comment]
Problem is already fixed on master. Closing this as duplicate. Will release the fix soon.
