### ISSUE TITLE
Code examples unable to scroll horizontally on Chrome

### ISSUE THREAD

**Issue by paddymoran** [aurelia/documentation#336]
**I'm submitting a bug report**

* **Operating System:**
OSX 10.12.4

* **Browser:**
Chrome 57

**Current behavior:**
Code examples aren't able to scroll horizontally in Chrome (works in Firefox). For example: [Dependency Injection Docs](http://aurelia.io/hub#/doc/article/aurelia/dependency-injection/latest/dependency-injection-basics/2) in the example **CustomerEditScreen Multiple Injection**.

**Expected/desired behavior:**

* **What is the expected behavior?**
Horizontal scrolling.

* **What is the motivation / use case for changing the behavior?**
Can't see all of the code in examples that are too wide, without copying and pasting the code somewhere else.

**Comment by Alexander-Taran** [comment]
can be closed
