### ISSUE TITLE
I18N Documentation not visible

### ISSUE THREAD

**Issue by marekpetak** [aurelia/documentation#337]
http://aurelia.io/hub.html#/doc/article/aurelia/i18n/latest/i18n-with-aurelia

- above link to i18n documentation is showing blank screen ...
- checked in lates browsers (Chrome, FF, Opera, Vivaldy, ...)

- not errors in console
- some templates are visible, but I'm too new to Aurelia to help ...

![capture](https://cloud.githubusercontent.com/assets/7045818/24906915/c0f4de9e-1eb1-11e7-8537-456f44ac266f.PNG)

**Comment by EisenbergEffect** [comment]
I think we may have a mal-formed document. I'll investigate. Thank you!

**Comment by marekpetak** [comment]
This seems to be working now.Thank you!
