### ISSUE TITLE
Aurelia Dialog Docs Typo

### ISSUE THREAD

**Issue by CristhianUNSa** [aurelia/documentation#338]
**I'm submitting a typo**

* **Doc Version:**
latest

There is a typo under settings. 'childConainer' should be 'childContainer'. [Link](http://aurelia.io/hub.html#/doc/article/aurelia/dialog/latest/dialog-basics/5)

**Comment by EisenbergEffect** [comment]
Would you be interested in contributing the fix? Here's the link to the source file: https://github.com/aurelia/dialog/blob/master/doc/article/en-US/dialog-basics.md

**Comment by CristhianUNSa** [comment]
Hi Rob, yes I will submit a PR.

**Comment by CristhianUNSa** [comment]
I was reading your "Git Commit Guidelines". Could the commit subject only be "fix typo" ?.
Message will be 
doc(aurelia-dialog): fix typo

Is this ok? without body and footer too.
It is my first precise rule pull request :smile:

**Comment by EisenbergEffect** [comment]
That is fine😀

**Comment by gheoan** [comment]
https://github.com/aurelia/dialog/pull/293 was merged and this can be closed.
