### ISSUE TITLE
why click is not triggering inside the info window?

### ISSUE THREAD

**Issue by shejin** [aurelia/documentation#342]
infoWindow: {content: `
                <div id="content">
                <div class="infowindow_panel" id="infowindow4">
                <div class="track_icon" id="td10652&amp;1"
                 title="show track" click.delegate ="spotFleetTrack()"></div>
                 </div><div class="s_iconclose" title="close" click.delegate="closeInfoBox(4,'spotfleet','',true)">
                 </div></div>
                  <div id="siteNotice"></div>
                  <h1 id="firstHeading" class="firstHeading">${x.vehicleName}</h1>
                  <div id="bodyContent">
                    <p>speed :${x.speed}</p>
                    <p>driver number: ${x.phoneNumber}</p>
                    <p>vehicle at: ${x.phoneNumber}</p>
                    <a id=${x.id} click.trigger="spotFleetTrack()">click me</a>
                  </div>
                </div>`

          }

**Comment by EisenbergEffect** [comment]
Please ask questions on Gitter or SO.
