### ISSUE TITLE
Faulty Link in Au Dialog:Basic

### ISSUE THREAD

**Issue by SolidStateLEDLighting** [aurelia/documentation#346]
Link in Plugins / Dialog / Dialog:Basics may not lead to the correct page.

Examine link called "manual bootstrapping"

in point 2 of "installing the Plugin".

I believe that link should point to 

http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/app-configuration-and-startup/4

ALSO -- after following this link -- I believe there is a section missing.   You are documenting Manual Bootstrapping -- and give a treatment to JSPM and Webpack -- but say nothing about Au Cli.   Why would Au Cli not apply to manual bootstrapping?    Is Au Cli by definition the non-manual way to bootstrap?   OR is there a section of information missing?

MORE:

Back in the Dialog doc --- None of the example code sections will change from js to ts examples when selected from the drop down box.

**Comment by EisenbergEffect** [comment]
@PWKad Can you look at this?

**Comment by Alexander-Taran** [comment]
attempt to fix this one: https://github.com/aurelia/site-generator/pull/1
