### ISSUE TITLE
Replaceable and replace-part

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/documentation#350]
I came across `replace-part` by chance when I saw @EisenbergEffect publish [EisenbergEffect/aurelia-composition-demo](https://github.com/EisenbergEffect/aurelia-composition-demo) and I wish I'd known about it months ago, before I started manually compiling views and attaching view slots. Even now that I know what to look for I can barely find any documentation on it (beside [this blog post](http://www.foursails.co/blog/semantic-template-parts/)), and its official status [seems to be unclear](https://stackoverflow.com/questions/38838725/is-replaceable-attribute-obsolete-in-aurelia-1-0). From what I can put together looking at half a dozen issues and SO questions, `replaceable` was supposed to be phased out in favor of slots, but then it turned out slots won't work in `if.bind` or `repeat.for`.

So to be perfectly clear: is `replace-part` supported and will it continue to be supported? If so, I'd love to see more documentation on its use added to the official documentation.

**Comment by EisenbergEffect** [comment]
Yes, it's definitely supported :)

**Comment by EisenbergEffect** [comment]
(Definitely needs more documentation.)
