### ISSUE TITLE
Documentation engine

### ISSUE THREAD

**Issue by tpiros** [aurelia/documentation#352]
It's not really a bug - more like a question: what is the engine that you guys use to generate the documentation pages? Thanks!

**Comment by EisenbergEffect** [comment]
It's hand-written. Also, it has a lot of issues. The good news is that I've been re-writing the entire thing and I've done it so we'll have a CLI that can generate the full Aurelia site, documentation and all. In the first pass, it's not really generalizable to other sites/projects, but it could be made to work that way in the future. In either case, we'll be open-sourcing that soon.
