### ISSUE TITLE
It's tough to find any instructions on how to create a plugin for Aurelia.

### ISSUE THREAD

**Issue by dkent600** [aurelia/documentation#353]
It's tough to find any instructions on how to create a plugin for Aurelia.  I'm not sure they exist.

**Comment by jauniuse** [comment]
It would be good to get a response on this one

**Comment by EisenbergEffect** [comment]
This would be a great question to ask on our Discrourse forum: https://discourse.aurelia.io/
One of the best way to learn how to build a plugin is to look at the skeletin-plugin repo, which sets you up to build a plugin. Another way is to look at the ux repo which is a collection of component plugins that we've built. There's very little special about building a plugin. An important thing to note is that you don't need to "build a plugin" unless you are building UI components that you want to share. If it's anything else, the best approach would be to just build standard ES modules.
