### ISSUE TITLE
route-recognizer API is not documented

### ISSUE THREAD

**Issue by gheoan** [aurelia/documentation#354]
**I'm submitting a feature request**

**Current behavior:**
Aurelia HUB does not include the route-recognizer library.

**Expected/desired behavior:**

* **What is the expected behavior?**
Aurelia HUB should include the route-recognizer library.

* **What is the motivation / use case for changing the behavior?**
Inspecting the API without looking at the source code.

**Comment by Alexander-Taran** [comment]
@EisenbergEffect is it an oversight?
I can see some of the modules in route-recognizer have comments with type info.

**Comment by EisenbergEffect** [comment]
I think we thought of this as more of an "internal" module. We hadn't had many use cases where people want or need to interact with it directly. In a future version of Aurelia, I think this might just get merged with the router itself.

**Comment by Alexander-Taran** [comment]
@EisenbergEffect is it a lot of work to add this to API docs? can I help with PR?

**Comment by EisenbergEffect** [comment]
Let me see if I can add it real quick.

**Comment by EisenbergEffect** [comment]
Ok, it's added and published. However, there is a ton of basic description stuff missing, so it doesn't look great if you browse it.

**Comment by Alexander-Taran** [comment]
@EisenbergEffect thank you!
@gheoan would you like to provide a PR to improve the docs for route-recognizer? or close this one?

**Comment by gheoan** [comment]
I have a branch for route-recognizer which adds more typescript types. Will send a PR when it's ready.
