### ISSUE TITLE
Aurelia HUB misprint

### ISSUE THREAD

**Issue by Jule-** [aurelia/documentation#357]
You wrote `export` instead of `exports`.

---

http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/the-aurelia-cli/10

A Legacy Library Dependency Copy
```
"dependencies": [
  {
    ...
    "export": "$"
  },
  ...
```

**Comment by avrahamcool** [comment]
I think the issue can be closed.
the section about aurelia cli was rewritten, and this piece of code is not there anymore.
