### ISSUE TITLE
Search for globalResources broken

### ISSUE THREAD

**Issue by nym** [aurelia/documentation#358]
**I'm submitting a bug report**

* **Browser:**
Chrome XX

**Current behavior:**
Search for 'globalResources' returns 1 match under API.

**Expected/desired behavior:**
Guides with 'globalResources' should show up too.

See all these results that Google was able to index: 
https://www.google.com/search?q=site:aurelia.io+globalResources

Specifically for 'globalResources', I was trying to find documentation on how to use the API for someone and eventually found http://aurelia.io/docs/templating/html-behaviors-introduction#global-resources

* **What is the motivation / use case for changing the behavior?**
Good docs shouldn't be invisible :)

**Comment by Alexander-Taran** [comment]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/1029452/170844894-52c7e56c-c69b-4b4e-8f35-6a0638cc489d.png">

@bigopon search fixed 
🤦🏻‍♂️
