### ISSUE TITLE
Typo: in Building Out the Contact Detail Screen

### ISSUE THREAD

**Issue by WisdomCorp** [aurelia/documentation#363]
There is additional **row** class in [Building Out the Contact Detail Screen](https://aurelia.io/docs/tutorials/creating-a-contact-manager#building-out-the-contact-detail-screen) in following line -

`<div class="form-group row">`

I thing the row class should be removed.

thanks

**Comment by Alexander-Taran** [comment]
Would you like to provide a pull request for it @WisdomCorp ? (-:
thanks

**Comment by EisenbergEffect** [comment]
This one has been fixed now. Thanks!
