### ISSUE TITLE
Issue in Contact Manager App.html

### ISSUE THREAD

**Issue by WisdomCorp** [aurelia/documentation#364]
In the **Step: Adding A loading Indicator** [here](https://aurelia.io/docs/tutorials/creating-a-contact-manager#next-steps)

below line generates error -
`<require from="bootstrap/css/bootstrap.css"></require>`

The error is -

> ERROR in ./src/app.html
Module not found: Error: Can't resolve 'bootstrap/css/bootstrap.css' in 'C:\Work\temp\aureliaTS\contactmanager\src'

PS: It seems to work fine, once I deleted the above code.

**Comment by Alexander-Taran** [comment]
ok. you don't need that require.
You already included that css in the main.ts/.js
If you could create a pull request removing that line from app.html source @ the step - would be great.
