### ISSUE TITLE
Logmanager api documentation

### ISSUE THREAD

**Issue by DickvdBrink** [aurelia/documentation#365]
**I'm submitting a bug report**

**Current behavior:**
https://aurelia.io/docs/api/framework/constant/LogManager
is showing that LogManager is a 
>LogManager: "/Users/EisenbergEffect/Documents/GitHub/aurelia-current/framework/node_modules/aurelia-logging/dist/aurelia-logging"

![image](https://user-images.githubusercontent.com/765657/48120577-cee40800-e272-11e8-8557-d9c193d0594b.png)

So it is showing some local path which a user can't do anything with.

* **What is the expected behavior?**
The actual shape of the LogManager or a link to: https://aurelia.io/docs/api/logging

**Comment by EisenbergEffect** [comment]
Looks like a bug in TSDoc that generates this data. LogManager is a bit of an artificial export anyway. Instead, consider just importing directly from the Logger module. LogManager is basically just the module object for the Logger, so it has the same exports.

**Comment by EisenbergEffect** [comment]
We'll look into this to see if we can easily fix it.

**Comment by EisenbergEffect** [comment]
Fixed.

**Comment by EisenbergEffect** [comment]
(Or, rather we removed it because TSDoc isn't handling it properly. It's the best we can do for now.)
