### ISSUE TITLE
display issue with basic binding example

### ISSUE THREAD

**Issue by avrahamcool** [aurelia/documentation#372]
the documentation shows nicely in the [github page](https://github.com/aurelia/documentation/blob/master/current/en-us/4.%20binding/1.%20basics.md).

![image](https://user-images.githubusercontent.com/5445320/50792135-a60cdd00-12cc-11e9-9018-9d9fececff19.png)

but looks wrong in the actual [documentation page](https://aurelia.io/docs/binding/basics#expression-syntax).

![image](https://user-images.githubusercontent.com/5445320/50792171-c177e800-12cc-11e9-96cb-77dd9372baa3.png)

maybe 
`` `foo${bar}baz${qux}quux` ``
should become
`` `foo\${bar}baz\${qux}quux` ``

### how can we test the result of a change in the documentation, to see how it will render in the real documentation pages?

**Comment by avrahamcool** [comment]
same behavior a few paragraphs later.
in github:

![image](https://user-images.githubusercontent.com/5445320/50792565-1ec06900-12ce-11e9-9849-5743d0e8c543.png)

in result documentation page:
![image](https://user-images.githubusercontent.com/5445320/50792585-2e3fb200-12ce-11e9-8616-cea50eec47d2.png)

**Comment by huochunpeng** [comment]
PR pls :-)

**Comment by avrahamcool** [comment]
Id love to, but how can I test my changes?
i need a way to transform the repo into pages the same way the documentation site does.
(is it covered here somewhere?)

**Comment by huochunpeng** [comment]
The doc is handled by https://github.com/aurelia/site-generator
But I have not tried since @EisenbergEffect switched to centralised doc, I am not sure how to do it.

@EisenbergEffect could you want to add some instruction to readme?

**Comment by EisenbergEffect** [comment]
It's a bit tricky to test it out locally. I have a todo on my list to create a "sandbox" within this repo and instructions on how to run it to test. I'll try to get that in place soon. Will probably be a week or two since I'm traveling. If you want to submit a PR, I'm happy to test it out and fix it if it doesn't work. It should just be the addition of the backslashes that's required.

**Comment by avrahamcool** [comment]
I'm not sure if this was published or not..
but the documentation result is still broken.

if it was published, we need to find the right fix to apply.

**Comment by EisenbergEffect** [comment]
It’s not published yet. Should go out today or tomorrow.

**Comment by avrahamcool** [comment]
@EisenbergEffect 
Sorry to bother you again with that.
the site is still not showing properly.
is the fix published?

**Comment by EisenbergEffect** [comment]
No apology necessary. I was on vacation and mis-accounted for what it would take me to catch up with work when I returned. So, this is on my list but I'm a bit behind. We've got several releases going out over the next few days. The docs will get updated with those changes and this one as part of that process. Thanks for your patience!
