### ISSUE TITLE
[Bug] using back-tic in header doesn't show in the site

### ISSUE THREAD

**Issue by avrahamcool** [aurelia/documentation#387]
When backtick are used as part of a Title, they are stripped from the actual result.

Github Page: https://github.com/aurelia/documentation/blob/master/current/en-us/4.%20binding/6.%20delegate-vs-trigger.md

![image](https://user-images.githubusercontent.com/5445320/53243968-2be4bc00-36b2-11e9-9fb8-74c5aa9f0056.png)

Site rendering: https://aurelia.io/docs/binding/delegate-vs-trigger#delegate-vs-trigger

![image](https://user-images.githubusercontent.com/5445320/53243947-1a031900-36b2-11e9-99f3-3f24d775d38b.png)

**Comment by avrahamcool** [comment]
This is very bizarre.

Iv'e found a lot of other places where backtick is used in titles, and they all render fine (I've checked them all).
the only place where it breaks is in the `capture` example. not sure what is different there.

![image](https://user-images.githubusercontent.com/5445320/53244785-94349d00-36b4-11e9-9a21-2d0c385d2f5e.png)

**Comment by EisenbergEffect** [comment]
Strange. Something in the underlying markdown library, but does seem very odd. I'll merge this. Thanks for the fix.

**Comment by avrahamcool** [comment]
escaping the bactick didn't work.
I think it's better to just remove it.
I'll create a new PR.

**Comment by EisenbergEffect** [comment]
Merged. Thank you!
