### ISSUE TITLE
Convention about src folder

### ISSUE THREAD

**Issue by rdarioduarte** [aurelia/documentation#4]
Would be nice to have a convention documented about the structure on the src folder.

As per our discussion with @janvanderhaegen on the gitter, he suggested:

"You should be able to just create those folders and throw them in, the built-in convention understands the 'views' and 'viewmodels' convention
but you'll have to update the routes in your app start to point to the correct viewmodel folder"

**Comment by EisenbergEffect** [comment]
Check the docs repo. I just added it on `docs.md`. It's not pushed to the official site yet. That will happen later today or tomorrow. But you can read it in the repo. It's at the end under a new section titled "Customization".
