### ISSUE TITLE
Navigation skeleton project doesn't quite match the tutorial

### ISSUE THREAD

**Issue by mtimms** [aurelia/documentation#41]
If you just download and run the Navigation Skeleton Project from the Getting Started page there's an upper value converter shown for the fullName binding in the Welcome.html. They should match, but probably nice to introduce it in the tutorial. Instant hit for any WPF/Silverlight devs!

**Comment by EisenbergEffect** [comment]
We'll be updating tour getting started guide for the beta soon.
