### ISSUE TITLE
Binding basics doc typo

### ISSUE THREAD

**Issue by davidtimovski** [aurelia/documentation#414]
In the [binding doc](https://github.com/aurelia/documentation/blob/master/current/en-us/4.%20binding/1.%20basics.md) there's a typo at the end of line 51. A `">` for some reason.

Small thing but it makes the docs look unprofessional when there's typos and mistakes around. I can make a PR if no one wants to bother with it.

**Comment by EisenbergEffect** [comment]
@davidtimovski We wold absolutely love a contribution to fix the issue. We highly value community assistance, esp. in making our docs great. Are you up for submitting a PR?

**Comment by davidtimovski** [comment]
Yep, I'll submit one tomorrow :)
