### ISSUE TITLE
Documentation for Observing Collections shows Typescript language elements in EsNext View

### ISSUE THREAD

**Issue by Alfhir** [aurelia/documentation#420]
**I'm submitting a bug report**
The documentation seems broken at this [point ](https://aurelia.io/docs/binding/observable-properties#observable-properties). A user that does not know Typescript might not understand.

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Browser:**
Firefox 67.04 (64bit)

* **Language:**
ESNext

**Current behavior:**
Example for "Configuring a Collection Observer" in EsNext imports via autoinject and uses typescipt in constructor.

```
import {BindingEngine, autoinject} from 'aurelia-framework';
  
  @inject(BindingEngine)
  export class App {
  
    myCollection = ["foo"];
  
    constructor(private bindingEngine) {
      let subscription = this.bindingEngine.collectionObserver(this.myCollection)
        .subscribe(this.collectionChanged.bind(this));
    }
  
    collectionChanged(splices) {
        // This will fire any time the collection is modified. 
    }
  }
```

[See](https://aurelia.io/docs/binding/observable-properties#observable-properties)

**Expected/desired behavior:**

  
```
import {BindingEngine} from 'aurelia-framework';

  @inject(BindingEngine)
  export class App {
    myCollection = ["foo"];
  
    constructor(bindingEngine) {
      this.bindingEngine = bindingEngine;
    }
  }
```
  
* **What is the motivation / use case for changing the behavior?**
Clean documentation

**Comment by EisenbergEffect** [comment]
Looks like a copy/paste error on our part. I'll get a fix in shortly. Thank you and we apologize for the confusion!
