### ISSUE TITLE
Add links to Push State requires server side support documentation

### ISSUE THREAD

**Issue by baerrach** [aurelia/documentation#430]
**I'm submitting a bug report**

**Current behavior:**
https://aurelia.io/docs/routing/configuration#options

The warning block says

> PushState requires server-side support. Don't forget to configure your server appropriately.

It should provide a link to the relevant section of the documentation that shows how to configure the server appropriately.

As a new user it is not obvious where this documentation might be, I had a quick scan of the main topics and couldn't find it.

**Comment by EisenbergEffect** [comment]
The tricky bit is that it’s different configuration depending on the server being used. Should we just provide a note with the webpack configuration? @baerrach What do you think the best way to handle this would be?

**Comment by baerrach** [comment]
I would use [Just Barely Good Enough](http://agilemodeling.com/essays/barelyGoodEnough.html) to answer that question.

Either the 
a) information is not relevant and can be deleted,
b) information is important and needs to be included.

You've marked the warning as needing server-side support so I think that is something that is important.

It needs at a minimum what features are necessary to get it to work server-side.

If there is also a working example for at least one server that would be good to include (on another page) and this should be enough for other people to base their solution off. If they think their solution is important enough then they can contribute it back.

**Comment by EisenbergEffect** [comment]
I added some more details to help point people in the right direction.
