### ISSUE TITLE
Aurelia validation docs - configuration in .json still needed?

### ISSUE THREAD

**Issue by bdelsaz** [aurelia/documentation#438]
Hi!
I am checking out the documentation regarding validation ,and after installation of the aurelia-validation package the instruction reads:

> If you're using the aurelia-cli, add the following configuration to your aurelia.json after you've installed the package with npm.
```
 {
    "name": "aurelia-validation",
    "path": "../node_modules/aurelia-validation/dist/amd",
    "main": "aurelia-validation"
  }
```
> [...] search your aurelia.json for aurelia-templating-resources [...]

The aurelia.json file under the aurelia_project does not have anything about aurelia-template-resources. It looks like this template-resources is now part of the packages.json file. 

Is the documentation still up to date?

My setup:
Library Version:
aurelia-cli v1.0.1
Environment

Operating System:
Windows 10

Node Version:
v10.15.3

NPM Version:
6.9.0

Browser:
Chrome Version 75.0.3770.100 (Official Build) (32-bit)

Language:
Typescript 3.1

Loader/bundler:
Webpack

**Comment by 3cp** [comment]
It is outdated, latest cli doesn't require user to add dep explicitly. CLI does all automatically.

I will remove the part from the doc.
