### ISSUE TITLE
GitHub rate limit reached

### ISSUE THREAD

**Issue by delebash** [aurelia/documentation#45]
Tried jspm registry config github, Invalid argument registry.
change to registry to endpoint in docs

GitHub rate limit reached. To increase the limit use GitHub authentication.
     Run jspm endpoint config github to set this up.

**Comment by EisenbergEffect** [comment]
What version of jspm are you running?

**Comment by delebash** [comment]
I am running jspm version 0.14.0

maybe version 0.15.x fixes this?

**Comment by delebash** [comment]
Yes I see in the comments that [0.15.0](https://github.com/jspm/jspm-cli/releases/tag/0.15.0) changed to endpoint to registry
