### ISSUE TITLE
Assets file not working with Chrome

### ISSUE THREAD

**Issue by rallets** [aurelia/documentation#482]
Hi, I'm not sure this is the correct repo.
I'm going through the documentation from [your website](https://aurelia.io/docs/tutorials/creating-a-contact-manager) and the link to download the [assets](https://aurelia.io/docs/tutorials/creating-a-contact-manager#adding-required-assets) is not working with Chrome (v. 91). It does work with Edge.
I hope this helps to improve the docs.

**Comment by 3cp** [comment]
The aurelia website is using https, but that link is somehow on http, not https `http://aurelia.io/downloads/contact-manager-assets.zip`. I guess Chrome blocked it because of some security related policy.

**Comment by rallets** [comment]
Tks @3cp I didn't notice the http/https thing, it make sense!
