### ISSUE TITLE
Tutorial contains broken link to App Configuration and Startup

### ISSUE THREAD

**Issue by Nallebeorn** [aurelia/documentation#488]
**I'm submitting a bug report**

**Current behavior:**
* Navigate to the guide's tutorial at [https://aurelia.io/docs/tutorials/creating-a-todo-app#rendering-the-app](https://aurelia.io/docs/tutorials/creating-a-todo-app#rendering-the-app).
* Click the link that reads "App Configuration and Startup".
* You are redirected to https://aurelia.io/fundamentals/app-configuration-and-startup, which gives a 404 error.

**Expected/desired behavior:**
* You should be redirected to https://aurelia.io/docs/fundamentals/app-configuration-and-startup/, which is the correct URL.

Interestingly, the repo seems to have the correct URL, as it was fixed in this PR: https://github.com/aurelia/documentation/pull/485

That PR was however merged one and a half years ago, so it doesn't seem right that this issue is still present on the live site.

**Comment by 3cp** [comment]
There is some missed regeneration of our site for a while. I raised a PR to our private github pages repo to update all docs.

@bigopon we probably should open up https://github.com/aurelia/aurelia.github.io.

**Comment by 3cp** [comment]
Published latest doc but found another issue.

The merged doc fix "../docs/..." did not work well, at least failed on Edge.

It should just use absolute path "/docs/..." as other pages use.

**Comment by bigopon** [comment]
> @bigopon we probably should open up https://github.com/aurelia/aurelia.github.io.

You meant making it non-private? I can do that, though I'm not sure what sensitive information in the repo itself, or its history may be leaked, since I only took over from @EisenbergEffect

**Comment by 3cp** [comment]
I will raise another PR for the site update.

**Comment by 3cp** [comment]
Site is updated.
