### ISSUE TITLE
Attached behavior example references undefined Element class

### ISSUE THREAD

**Issue by axefrog** [aurelia/documentation#50]
The following code snippet is erroneous:

```js
import {Behavior} from 'aurelia-framework';

export class Show {
  static metadata(){
    return Behavior
      .attachedBehavior('show')
      .withProperty('value', 'valueChanged', 'show');
  }

  static inject() { return [Element]; }
  constructor(element) {
    this.element = element;
  }

  valueChanged(newValue){
    if (newValue) {
      this.element.classList.remove('aurelia-hide');
    } else {
      this.element.classList.add('aurelia-hide');
    }
  }
}
```

The inject function references the `Element` class but it is not imported at the top of the snippet, and nowhere else in the documentation indicates where to import `Element` from either.

**Comment by axefrog** [comment]
I'm an idiot. Sorry.

**Comment by zewa666** [comment]
Just to keep a notice in case anybody searches this. Element is a native JS code, that's why you don't have to import it.
