### ISSUE TITLE
Suggestion: mention that attached() is the equivalent for DOMReady 

### ISSUE THREAD

**Issue by devmondo** [aurelia/documentation#61]
the question always pops up and a lot of people asking, why my plugin is not working, why jquery stuff is not working, and the usual answer is do it in ```attached ()```.

 so i think it would be helpful to mention in the docs that ```attached ()``` is the equivalent for DOMReady, this way a lot of people wont have to ask this question and for those who are coming form jquery background it will instantly click for them.

**Comment by jdanyow** [comment]
related to https://github.com/aurelia/skeleton-navigation/issues/72

**Comment by EisenbergEffect** [comment]
Current docs now explain the meaning of the attached callback and it is in line with web components meaning as well.
