### ISSUE TITLE
Documentation for navigationStrategy

### ISSUE THREAD

**Issue by zewa666** [aurelia/documentation#68]
need to document the new feature about navigationStrategy

**Comment by EisenbergEffect** [comment]
I believe it's there now.

**Comment by 7Pass** [comment]
@EisenbergEffect  Can you add a note to navigationStrategy implementations that if the route has been navigated to before, you will need to set moduleId of NavigationInstruction.config.viewPorts.default as well? I spent quite sometime not understanding how navigationStrategy work and about to give up when I finally notice that viewPorts had its moduleId values as well, and that was the reason navigationStrategy seemed to not work for my case.

**Comment by fragsalat** [comment]
Searched for it as well quite a time to recognize that setting instruction.config.moduleId isn't enough after second routing.
