### ISSUE TITLE
Generate automatically ID-Attrs for headings

### ISSUE THREAD

**Issue by zewa666** [aurelia/documentation#7]
It would be pretty nice if the markdown compiler used for the webpage could automatically create ID-Attributes for the headings. The reason is when you send links to people you don't have to say "go to docs and section XYZ" but could directly send a link with the proper anchor.

**Comment by EisenbergEffect** [comment]
Yeah. That would be nice. Unfortunately, I don't think the site generator I'm using supports it. I need to try to find out more.

**Comment by EisenbergEffect** [comment]
Ultimately, this will be replaced with a Aurelia docs app...

**Comment by zewa666** [comment]
For now a workaround may be to include normal <hx> tags with an ID.

**Comment by zewa666** [comment]
Seems to be solved with the new design so I'm closing this issue
