### ISSUE TITLE
Initial Documentation Wireframe 

### ISSUE THREAD

**Issue by scriswell** [aurelia/documentation#76]
@EisenbergEffect Have you included the outline we discussed? I'd like to use it as a base for the wireframes.

**Comment by EisenbergEffect** [comment]
@scriswell I've added the high level notes to the wiki here: https://github.com/aurelia/documentation/wiki/Docs-App-High-Level-Overview

**Comment by scriswell** [comment]
@EisenbergEffect This tasks is for creating the wireframe. I'd like to re-open and assign it back to me.

**Comment by scriswell** [comment]
@EisenbergEffect much thanks.

**Comment by PWKad** [comment]
I'm not sure if it is part of this but another thing that would be nice to include is a mock of how the tabbed content should look.  Similar to how [Twilio's docs](https://www.twilio.com/docs/api/rest/making-calls#example-1) have tabbable code samples that can show the same thing in multiple languages (in our case it would be ES5/6/7 / TypeScript / CoffeeScript)

**Comment by EisenbergEffect** [comment]
Yes. Will send out wireframes soon.
