### ISSUE TITLE
Build Process Improvements

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/documentation#82]
I've been thinking that we might be able to improve the build process of Aurelia around a few scenarios that have recently come up. Here's what I am proposing:

* Every repository should contain the following src files
    * imports.js - contains all the ES6 import statements for the library
    * exports.js - contains all the ES6 export statements for the library.
    * classes - one file per ES6 class. No imports or exports. Decorated with Flow types.
    * interfaces.js - contains any TypeScript interfaces needed to define "shapes" which are not defined as classes in our ES6 API
* The build process will concatenate all these files into a single index.js with the imports at the top, the classes/interfaces in the middle and the exports at the bottom.
* The build process will use Babel to compile the index.js file, which will strip the Flow types and interface definitions and generate all our supported module formats.
* The build process will use the Babel compiler with a d.ts plugin to generate a single d.ts file for the library, based on the Flow types and interfaces.
* The build process will copy the generated d.ts file into each module format folder so that it can be distributed with our source via standard package managers.

Here's what I think we can get from this:

* A single file for each Aurelia library will result in less http requests during debug scenarios, making the development experience smoother.
* A single file will reduce the amount of library code that the Babel compiler generates. Instead of it having to generate it for each class file (today), it only generates the helpers once per library. This makes Aurelia smaller.
* A single file will reduce the amount of runtime module lookup required by the ES6 loader. Thus startup should be faster.
* The flow types and plugin will allow us to get a solid d.ts file for each library and always keep it in sync with every release version.
* We preserve the flexibility of leveraging the Babel compiler.
* We **might** be able to also compile with the TS compiler directly.

**Comment by EisenbergEffect** [comment]
I forgot to mention, that breaking things down into these files, might make using source maps with aurelia itself a bit more awkward since the source map will point to the combined index.js file. I don't think it's a big deal, but want to mention it here.

**Comment by cmichaelgraham** [comment]
would this also alleviate the circular reference issues we were having?

**Comment by EisenbergEffect** [comment]
@cmichaelgraham There would be no circular refs, yes.
