### ISSUE TITLE
`Get started` tutorial is not very straightforward

### ISSUE THREAD

**Issue by Nness** [aurelia/documentation#87]
Get started tutorial have way too many opinions. 
* Babel
* Gulp
* Node.js
* etc etc

A lot of 'you can do it with something else but we think this is better so go here and learn it'. When you have that many dependency on a simple start up project, how many developer will stop by and get through it?

If you take look at angularjs or even durandal's get start. It just list a simple html with some javascript reference and its done.

Shouldn't that `get started` tutorial can be done with notepad with least effort and get something done in a few min?

When someone look at new libraries or framework as non frontend developer, most of time they will try to check out how easier it is to get something in to their project without any advanced tools.

Babel have browser.js, it doesn't even require you to pre-compile your code.

The easier it is to do a `hello world` app and with advanced setup afterward, the easier to get people from different skill range to hook up.

**Comment by EisenbergEffect** [comment]
This is an alpha. Things will be improved for release.
