### ISSUE TITLE
Support loading via script tag(s) with no module loader

### ISSUE THREAD

**Issue by bryanrsmith** [aurelia/documentation#89]
We should figure out how to bundle all the libraries together in a way that can be loaded with one or two script tags. This would make it easy for people to try out Aurelia without having to install any tooling at all. It would also simplify use cases like jsbin, jsfiddle, etc..

**Comment by EisenbergEffect** [comment]
I'm going to close this for now since we have the new beginner kits which don't require any installation.

**Comment by justinobney** [comment]
I think it would be very be able to try things out in JSBin/JSFiddle, etc....

**Comment by philiphendry** [comment]
I agree. I'd even take it a step further and get Aurelia integrated with JSFiddle/Plunker/JSBin so it's just a click away - AngularJS is already there and I'd like to see Aurelia 'advertised' alongside it!

**Comment by PWKad** [comment]
We do have an official plunker that's always on latest at http://bit.ly/aurelia-plunker

**Comment by philiphendry** [comment]
Thanks for getting back @PWKad. I've just tried that plunk but it fails with over a hundred errors downloading resources from cdn.rawgit.com - it looks like some of the resources aren't being delivered with the Access-Control-Allow-Origin header.

**Comment by philiphendry** [comment]
Just a thought to anyone who has more time than me to look into this... I just came across a javascript library call [jbatch](http://iomash.com/) and wondered whether it could be made to bootstrap SystemJS and Aurelia. It's an intriguing system and it's the [bootstrap](http://codepen.io/iomash/pen/xbMwWp) command that got me thinking about Aurelia.
