### ISSUE TITLE
add tags like "new"  to doc content

### ISSUE THREAD

**Issue by devmondo** [aurelia/documentation#90]
right now, we cant know what was newly added to the docs because there is nothing that shows that, and we have to reread the whole docs again to find the new content additions, therefore i suggest implementing some kind of tagging system, this will let us instantly dig to the latest content.

some tags i suggest
*  new
* deprecated 

i have attached a stupid mockup image, hope this helps
![aurelia-docs-new](https://cloud.githubusercontent.com/assets/1266367/7659499/69b9ab42-fb53-11e4-8a22-705c7bbe7b90.jpg)

**Comment by davidpeden3** [comment]
Great idea. Would be super useful if you could specify "since" or "between" (possibly even "prior to") with a dropdown list of releases that would aggregate changes.

**Comment by devmondo** [comment]
:+1: to @davidpeden3

**Comment by EisenbergEffect** [comment]
New, fully-versioned docs on the way soon.
