### ISSUE TITLE
Behaviors gets too much attention in the documentation

### ISSUE THREAD

**Issue by bastienJS** [aurelia/documentation#92]
Getting more interested in aurelia, I just browsed the documentation: http://aurelia.io/docs.html

Type in the browser search: "behavior" I find 14 results. That seems ok at first sight.

But when I look closer at the results I am totally missing something.

I would have expected a headliner like "BEHAVIORS" - what they are and where you need them bla....

Please improve that :-)

**Comment by EisenbergEffect** [comment]
We are planning a while new set of docs in the near future :) The term "behaviors" is a generic way of referring to Aurelia's custom elements and custom attributes (including custom template controllers).

**Comment by zewa666** [comment]
Sry this was my fault, I had a conversation with @bastienJS and understood he meant Value Converters, which are currently not explicitly mentioned in the docs
